@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Create Order API\n[createOrders]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")

    Boundary(middleware, "middleware order API\n[Component]"){

        Component(verify_token, "verifyToken", "Middleware | NodeJS", "Middleware check bearer token\n{ms-order}")
        Component(validate_body, "validateRequestBody", "Middleware | NodeJS", "Middleware for validate request body\n{ms-order}")

    }
    
    Boundary(api, "createOrders API\n[Component]"){

        Component(createOrders, "createOrders", "Function | NodeJS", "API for insert data order\n{ms-order}")

    }

    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for order momo x")

Rel_D(web_momo_x, verify_token, "1. Check token request")
Rel_D(verify_token, validate_body, "2. Validate request query")
Rel_D(validate_body, createOrders, "3. Request create order")
Rel_D(createOrders, momo_x_storage, "4. Insert data order")
Rel_D(createOrders, momo_x_storage, "5. Insert data order payload")
Rel_D(createOrders, momo_x_storage, "6. Insert data order log")


SHOW_LEGEND()
@enduml