@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title updateCarData API\n[NodeJs Mobil API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "updateCarData API\n[Component]"){
Component(auth_middleware, "auth.validate", "Middleware | NodeJs", "Authentication Middleware for validate Function\n(NodeJs Mobil API)")
Component(mobil_controller, "Mobil Controller", "Controller | NodeJs", "Controller for Mobil Related Function\n(NodeJs Mobil API)")
Component(updateCarData, "updateCarData", "Function | NodeJs", "Function for update car data\n(NodeJs Mobil API)")
Component(Mobilupdate, "Mobil.update", "Function | NodeJs", "Function for update car data\n(NodeJs Mobil API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request update car data by car ID")
Rel_D(auth_middleware, mobil_controller, "2. Request update car data by car ID")
Rel_D(mobil_controller, updateCarData, "3. Request update car data by car ID")
Rel_D(updateCarData, Mobilupdate, "4. Update car data by car ID")
Rel_D(Mobilupdate, database, "5. Update car data by car ID")

@enduml