@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title NodeJs Service Platform Bengkel API

Component(Web_Moservice, "API Gateway", "Services | TypeScript", "All API used by moservice.id")
Component(API, "NodeJs Service Platform Bengkel API", "Repository | NodeJs", "Repository for NodeJs Bengkel Related Function")

Boundary(api, "NodeJs Bengkel API\n[Component]"){
Component(bengkelDetail, "Bengkel Detail", "Function | TypeScript", "Function for Retrieve Bengkel detail data\n(NodeJs Bengkel API)")
Component(callCounter, "Call Counter", "Function | TypeScript", "Function for Get Call Counter data\n(NodeJs Bengkel API)")
Component(countListApp, "countListApp", "Function | NodeJs", "Function for Count List App Notification data\n(NodeJs Bengkel API)")
Component(create, "Create Bengkel", "Function | NodeJs", "Function for Create Bengkel data, Create Group Bengkel data, Create Ref Bengkel data\n(NodeJs Bengkel API)")
Component(createBusiness, "createBusiness", "Function | NodeJs", "Function for Create Business data\n(NodeJs Bengkel API)")
Component(createImages, "Create Image", "Function | NodeJs", "Function for Create bengkel Image data, Create mission Image path\n(NodeJs Bengkel API)")
Component(createMission, "createMission", "Function | NodeJs", "Function for Create mission data\n(NodeJs Bengkel API)")
Component(creater, "Create Notification", "Function | NodeJs", "Function for Create Notification data, Create Notification Image data\n(NodeJs Bengkel API)")
Component(deletedBengkel, "Delete Bengkel", "Function | NodeJs", "Function for Delete Bengkel data, Delete Change Image bengkel data, Delete Bengkel Image data, Delete Group Bengkel data, Delete Ref Bengkel data\n(NodeJs Bengkel API)")
Component(deletedMission, "Delete Mission", "Function | NodeJs", "Function for Delete Mission data, Delete Mission image path\n(NodeJs Bengkel API)")

Component(deleteNotification, "Delete Notification", "Function | NodeJs", "Function for Delete Notification data, Delete Notification Image data\n(NodeJs Bengkel API)")
Component(deleteFacilityImages, "deleteFacilityImages", "Function | NodeJs", "Function for Delete Facility Image data\n(NodeJs Bengkel API)")
Component(exportDataBengkel, "exportDataBengkel", "Function | NodeJs", "Function for Export data bengkel\n(NodeJs Bengkel API)")
Component(filter, "filter", "Function | NodeJs", "Function for Filter bengkel data\n(NodeJs Bengkel API)")
Component(getAllCarBrand, "Get Brand", "Function | NodeJs", "Function for Get All car Brand, Get Brand by Bengkel\n(NodeJs Bengkel API)")
Component(getAllCarModel, "Get Model", "Function | NodeJs", "Function for Get All car Model, Get all Car Model by Brand ID, Get Car Models by Bengkel and Brand data\n(NodeJs Bengkel API)")
Component(getApproveCountByDateGroupByCriteria, "getApproveCountByDateGroupByCriteria", "Function | NodeJs", "Function for Get Approve Count by Date Group by Criteria data\n(NodeJs Bengkel API)")
Component(getCaraBayarById, "Get Cara bayar", "Function | NodeJs", "Function for Get Cara Bayar by ID, Get list cara bayar\n(NodeJs Bengkel API)")
Component(getCityById, "Get City", "Function | NodeJs", "Function for Get bengkel City by ID, Get Province City, Get Nearest bengkel data, Get Promo bengkel cities data\n(NodeJs Bengkel API)")
Component(getNotif, "Get Notification", "Function | NodeJs", "Function for Get detail App Notification data, Get Detail Notification data, Get FCM data, Get List App, Get List Notification\n(NodeJs Bengkel API)")

Component(getDetailByPromoID, "getDetailByPromoID", "Function | NodeJs", "Function for Get Detail by promo ID data, get Detail Ref bengkel data\n(NodeJs Bengkel API)")
Component(getGroupBengkelByID, "Get Bengkel", "Function | NodeJs", "Function for Get Group bengkel data by ID, Get HO data by Bengkel ID, Get bengkel data by HOID, Get List bengkel option, Get List Tipe Servis, Get Daily quota count data by Bengkel ID\n(NodeJs Bengkel API)")
Component(getListMission, "Get Mission", "Function | NodeJs", "Function for Get List Mission data, Get Mission detail Progress data, Get Mission Rank data, Retrieve Tier Mission list data, Get Tier by Mission ID\n(NodeJs Bengkel API)")
Component(getStats, "getStats", "Function | NodeJs", "Function for Get bengkel Stats data\n(NodeJs Bengkel API)")
Component(importGooglePlaceId, "importGooglePlaceId", "Function | NodeJs", "Function for Import Google Place ID\n(NodeJs Bengkel API)")
Component(insertMapVideo, "insertMapVideo", "Function | NodeJs", "Function for Insert map video\n(NodeJs Bengkel API)")
Component(missionRegistration, "Mission Registration", "Function | NodeJs", "Function for Register Mission data, update Mission registration data\n(NodeJs Bengkel API)")
Component(read, "Read Bengkel", "Function | NodeJs", "Function for Read Bengkel data, Read Bengkel data by ID, Read Workshop by ID, Read Multi Condition Bengkel, Read By ID Detail\n(NodeJs Bengkel API)")
Component(reads, "Read Businesss", "Function | NodeJs", "Function for Read Business data, Read Multi Condition Business data\n(NodeJs Bengkel API)")
Component(searchBengkel, "searchBengkel", "Function | NodeJs", "Function for Search bengkel data\n(NodeJs Bengkel API)")

Component(update, "Update Bengkel", "Function | NodeJs", "Function for Update bengkel data, Update Group Bengkel data, Update Quota by Bengkel ID, Update Ref Bengkel, Update App\n(NodeJs Bengkel API)")
Component(updates, "Update Business", "Function | NodeJs", "Function for Update Business data\n(NodeJs Bengkel API)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, API, "Request use Function Related to Mobil")

Rel_D(API, bengkelDetail, "Request Retrieve Bengkel detail data")
Rel_D(API, callCounter, "Request Get Call Counter data")
Rel_D(API, countListApp, "Request Count List App Notification data")
Rel_D(API, create, "Request Create Bengkel data, Create Group Bengkel data, Create Ref Bengkel data")
Rel_D(API, createBusiness, "Request Create Business data")
Rel_D(API, createImages, "Request Create bengkel Image data, Create mission Image path")
Rel_D(API, createMission, "Request Create mission data")
Rel_D(API, creater, "Request Create Notification data, Create Notification Image data")
Rel_D(API, deletedBengkel, "Request Delete Bengkel data, Delete Change Image bengkel data, Delete Bengkel Image data, Delete Group Bengkel data, Delete Ref Bengkel data")
Rel_D(API, deletedMission, "Request Delete Mission data, Delete Mission image path")

Rel_D(API, deleteNotification, "Request Delete Notification data, Delete Notification Image data")
Rel_D(API, deleteFacilityImages, "Request Delete Facility Image data")
Rel_D(API, exportDataBengkel, "Request Export data bengkel")
Rel_D(API, filter, "Request Filter bengkel data")
Rel_D(API, getAllCarBrand, "Request Get All car Brand, Get Brand by Bengkel")
Rel_D(API, getAllCarModel, "Request Get All car Model, Get all Car Model by Brand ID, Get Car Models by Bengkel and Brand data")
Rel_D(API, getApproveCountByDateGroupByCriteria, "Request Get Approve Count by Date Group by Criteria data")
Rel_D(API, getCaraBayarById, "Request Get Cara Bayar by ID, Get list cara bayar")
Rel_D(API, getCityById, "Request Get bengkel City by ID, Get Province City, Get Nearest bengkel data, Get Promo bengkel cities data")
Rel_D(API, getNotif, "Request Get detail App Notification data, Get Detail Notification data, Get FCM data, Get List App, Get List Notification")

Rel_D(API, getDetailByPromoID, "Request Get Detail by promo ID data, get Detail Ref bengkel data")
Rel_D(API, getGroupBengkelByID, "Request Get Group bengkel data by ID, Get HO data by Bengkel ID, Get bengkel data by HOID, Get List bengkel option, Get List Tipe Servis, Get Daily quota count data by Bengkel ID")
Rel_D(API, getListMission, "Request Get List Mission data, Get Mission detail Progress data, Get Mission Rank data, Retrieve Tier Mission list data, Get Tier by Mission ID")
Rel_D(API, getStats, "Request Get bengkel Stats data")
Rel_D(API, importGooglePlaceId, "Request Import Google Place ID")
Rel_D(API, insertMapVideo, "Request Insert map video")
Rel_D(API, missionRegistration, "Request Register Mission data, update Mission registration data")
Rel_D(API, read, "Request Read Bengkel data, Read Bengkel data by ID, Read Workshop by ID, Read Multi Condition Bengkel, Read By ID Detail")
Rel_D(API, reads, "Request Read Business data, Read Multi Condition Business data")
Rel_D(API, searchBengkel, "Request Search bengkel data")

Rel_D(API, update, "Request Update bengkel data, Update Group Bengkel data, Update Quota by Bengkel ID, Update Ref Bengkel, Update App")
Rel_D(API, updates, "Request Update Business data")


Rel_D(bengkelDetail, database, "Retrieve Bengkel detail data")
Rel_D(callCounter, database, "Get Call Counter data")
Rel_D(countListApp, database, "Count List App Notification data")
Rel_D(create, database, "Create Bengkel data, Create Group Bengkel data, Create Ref Bengkel data")
Rel_D(createBusiness, database, "Create Business data")
Rel_D(createImages, database, "Create bengkel Image data, Create mission Image path")
Rel_D(createMission, database, "Create mission data")
Rel_D(creater, database, "Create Notification data, Create Notification Image data")
Rel_D(deletedBengkel, database, "Delete Bengkel data, Delete Change Image bengkel data, Delete Bengkel Image data, Delete Group Bengkel data, Delete Ref Bengkel data")
Rel_D(deletedMission, database, "Delete Mission data, Delete Mission image path")

Rel_D(deleteNotification, database, "Delete Notification data, Delete Notification Image data")
Rel_D(deleteFacilityImages, database, "Delete Facility Image data")
Rel_D(exportDataBengkel, database, "Export data bengkel")
Rel_D(filter, database, "Filter bengkel data")
Rel_D(getAllCarBrand, database, "Get All car Brand, Get Brand by Bengkel")
Rel_D(getAllCarModel, database, "Get All car Model, Get all Car Model by Brand ID, Get Car Models by Bengkel and Brand data")
Rel_D(getApproveCountByDateGroupByCriteria, database, "Get Approve Count by Date Group by Criteria data")
Rel_D(getCaraBayarById, database, "Get Cara Bayar by ID, Get list cara bayar")
Rel_D(getCityById, database, "Get bengkel City by ID, Get Province City, Get Nearest bengkel data, Get Promo bengkel cities data")
Rel_D(getNotif, database, "Get detail App Notification data, Get Detail Notification data, Get FCM data, Get List App, Get List Notification")

Rel_D(getDetailByPromoID, database, "Get Detail by promo ID data, get Detail Ref bengkel data")
Rel_D(getGroupBengkelByID, database, "Get Group bengkel data by ID, Get HO data by Bengkel ID, Get bengkel data by HOID, Get List bengkel option, Get List Tipe Servis, Get Daily quota count data by Bengkel ID")
Rel_D(getListMission, database, "Get List Mission data, Get Mission detail Progress data, Get Mission Rank data, Retrieve Tier Mission list data, Get Tier by Mission ID")
Rel_D(getStats, database, "Get bengkel Stats data")
Rel_D(importGooglePlaceId, database, "Import Google Place ID")
Rel_D(insertMapVideo, database, "Insert map video")
Rel_D(missionRegistration, database, "Register Mission data, update Mission registration data")
Rel_D(read, database, "Read Bengkel data, Read Bengkel data by ID, Read Workshop by ID, Read Multi Condition Bengkel, Read By ID Detail")
Rel_D(reads, database, "Read Business data, Read Multi Condition Business data")
Rel_D(searchBengkel, database, "Search bengkel data")

Rel_D(update, database, "Update bengkel data, Update Group Bengkel data, Update Quota by Bengkel ID, Update Ref Bengkel, Update App")
Rel_D(updates, database, "Update Business data")