@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title countListApp Notification API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "countListApp Notification API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification")
    Component(bengkel, "Notifikasi Controller", "Controller | NodeJs", "Controller for Notification Function related\n(NodeJs Bengkel API)")

    Component(countListApp, "countListApp", "Function | NodeJs", "Function for Count List App Notification data\n(NodeJs Bengkel API)")
    Component(countListApps, "Notifikasi.countListApp", "Function | NodeJs", "Function for Count List App Notification data\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Count List App Notification data")

Rel(auth_middleware, bengkel, "2. Request Count List App Notification data")
Rel(bengkel, countListApp, "3. Request Count List App Notification data")
Rel(countListApp, countListApps, "4. Request Count List App Notification data")
Rel(countListApps, database, "5. Count List App Notification data")

@enduml