@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getApproveCountByDateGroupByCriteria Moadmin API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "getApproveCountByDateGroupByCriteria Moadmin API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification\n(NodeJs Bengkel API)")
    Component(bengkel, "Bengkel Stat Controller", "Controller | NodeJs", "Controller for Bengkel Stat Function related\n(NodeJs Bengkel API)")

    Component(getApproveCountByDateGroupByCriteria, "getApproveCountByDateGroupByCriteria", "Function | NodeJs", "Function for Get Approve Count by Date Group by Criteria data\n(NodeJs Bengkel API)")
    Component(countApproveByDateGrouppedByParam, "Bengkel.countApproveByDateGrouppedByParam", "Function | NodeJs", "Function for Count Approve by date Groupped by param data\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Get Approve Count by Date Group by Criteria data")
Rel(auth_middleware, bengkel, "2. Request Get Approve Count by Date Group by Criteria data")
Rel(bengkel, getApproveCountByDateGroupByCriteria, "3. Request Get Approve Count by Date Group by Criteria data")
Rel(getApproveCountByDateGroupByCriteria, countApproveByDateGrouppedByParam, "4. Request Count Approve by date Groupped by param data")
Rel(countApproveByDateGrouppedByParam, database, "5. Count Approve by date Groupped by param data")

@enduml