@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getDetailApp Notification API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "getDetailApp Notification API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification")
    Component(bengkel, "Notifikasi Controller", "Controller | NodeJs", "Controller for Notification Function related\n(NodeJs Bengkel API)")

    Component(getDetailApp, "getDetailApp", "Function | NodeJs", "Function for Get detail App Notification data\n(NodeJs Bengkel API)")
    Component(getDetailApps, "Notifikasi.getDetailApp", "Function | NodeJs", "Function for Get detail App Notification data\n(NodeJs Bengkel API)")
    Component(updateIsRead, "Notifikasi.updateIsRead", "Function | NodeJs", "Function for Update Notification Read Status data\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Get detail App Notification data")

Rel(auth_middleware, bengkel, "2. Request Get detail App Notification data")
Rel(bengkel, getDetailApp, "3. Request Get detail App Notification data")
Rel(getDetailApp, getDetailApps, "4. Request Get detail App Notification data")
Rel(getDetailApp, updateIsRead, "6. Request Update Notification Read Status data")

Rel(getDetailApps, database, "5. Request Get detail App Notification data")
Rel(updateIsRead, database, "7. Request Update Notification Read Status data")
@enduml