@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getModelsByBengkelAndBrandApp Moservice API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "getModelsByBengkelAndBrandApp Moservice API\n[Component]"){
    Component(bengkel, "Bengkel Mobil Controller", "Controller | NodeJs", "Controller for Bengkel Mobil Function related\n(NodeJs Bengkel API)")

    Component(getModelsByBengkelAndBrandApp, "getModelsByBengkelAndBrandApp", "Function | NodeJs", "Function for Get Car Models by Bengkel and Brand data\n(NodeJs Bengkel API)")
    Component(getCarModelsByBengkelAndBrandApp, "Brand.getCarModelsByBengkelAndBrandApp", "Function | NodeJs", "Function for Get Car Models by Bengkel and Brand data\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, bengkel, "1. Request Get Brands data By Bengkel")
Rel(bengkel, getModelsByBengkelAndBrandApp, "2. Request Get Brands data By Bengkel")
Rel(getModelsByBengkelAndBrandApp, getCarModelsByBengkelAndBrandApp, "3. Get Brands data By Bengkel")
Rel(getCarModelsByBengkelAndBrandApp, database, "4. Get Brands data By Bengkel")

@enduml