@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title Component Diagram for Consume messages from a RabbitMQ queue related to birthday notifications\n (utils/utils.js)
Boundary(api, "consumeBD API\n[Component]"){
    AddProperty("Path", "ms-notification\utils\utils.js")
    Component(consumeBD, "consumeBD", "Function | NodeJs", "Function for Consume messages from a RabbitMQ queue related to birthday notifications")
    Component(createMqConnection, "mq.createMqConnection", "Function | NodeJs", "Function for Create MQ Connection")
    Component(connect, "amqp.connect", "Function | NodeJs", "Function for Connect Object")
    Component(createChannel, "connection.createChannel", "Function | NodeJs", "Function for Create Channel")
    Component(getQueueName, "mq.getQueueName", "Function | NodeJs", "Function for Get Queue Name")
    Component(assertQueue, "channel.assertQueue", "Function | NodeJs", "Function for Assert Queue")
    Component(consume, "channel.consume", "Function | NodeJs", "Function for Consume Queue")

}
AddProperty("URL", "process.env.ONE_SIGNAL_NOTIF_URL")
AddProperty("Service", "ONE SIGNAL NOTIF")
Component(ONE, "ONE Signal", "Function | NodeJs", "Function for Retrieve One Signal Responses")

AddProperty("URL", "process.env.MS_ACTIVITY + '/activity'")
AddProperty("Repository", "ms-activity")
Component(activity, "activityResponse", "Function | NodeJs", "Function for Create Activity")

Rel(consumeBD, createMqConnection, "1. Request Consume messages from a RabbitMQ queue related to birthday notifications")
Rel(createMqConnection, connect, "2. Connect Object")
Rel(createMqConnection, createChannel, "3. Create Channel")
Rel(consumeBD, getQueueName, "4. Get Queue Name ('notification_birthday')")
Rel(consumeBD, assertQueue, "5. Assert Queue")
Rel(consumeBD, consume, "6. Consume Queue")
Rel(consume, ONE, "7. Retrieve One Signal Responses Responses")
Rel(consume, activity, "7. Create Activity")

@enduml