@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()
title Moservice.id System\n(Component Diagram)
Container(A, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Container(B, "Moserviceadmin", "Website | JavaScript", "moservice.id main services for Admin")
Container(C, "Bengkel App", "Application | React Native", "moservice.id main services for Partner Bengkel")
Boundary(api, "Moservice.id System API\n(Component Diagram)"){
Component(b, "API Gateway", "Services | TypeScript", "All API used by moservice.id")
Component(c, "Auth API", "Services | NodeJs", "API For Authentication Process")
Component(d, "Bengkel Service API", "Services | NodeJs", "API For Manage Bengkel & Bengkel Group\n(Search, CRUD)")
Component(e, "Booking Service API", "Services | NodeJs", "API For Manage Booking\n(Search, Create)")
Component(f, "Content Service API", "Services | NodeJs", "API For Manage Content\n(Banner, Promo, Voucher)")
Component(h, "Mobil Service API", "Services | NodeJs", "API For Manage Product data\n(Vehicle data, CRUD)")
Component(k, "User API", "Services | NodeJs", "API For Manage User\n(Search, CRUD User data, Account Management(Profile, Password)")
Component(i, "Notification Service API", "Services | NodeJs", "API For Manage Notification\n(CRUD Notification)")
Component(j, "Payment API", "Services | NodeJs", "API For Manage Payment\n(Search, Show, CRUD, Invoice, Payment Method)")
}
System_Ext(l, "External System", "External API for OTP, Notification, Payment Service & Disbursement")
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel(A, b, "Login, Register & Manage Vehicle Request")
Rel(B, b, "Schedule Confirmation & Content Management Request")
Rel(C, b, "Booking Confirmation & Setting Bengkel Data")
Rel(b, c, "Login, Authentication, Validation")
Rel(b, d, "Submit data bengkel/bengkel group")
Rel(b, e, "Submit booking data")
Rel(b, f, "Get Content info")
Rel(b, h, "Get Product info")
Rel(b, i, "Request Send Notification")
Rel(b, j, "Get Payment Info")
Rel(b, k, "Submit Changes")
Rel_R(i, l, "Request OTP, Request Notification")
Rel_D(j, l, "Submit Payment Disbursement")

Rel(c, database, "CRUD Request")
Rel(d, database, "CRUD Request")
Rel(e, database, "CRUD Request")
Rel(f, database, "CRUD Request")
Rel(h, database, "CRUD Request")
Rel(i, database, "CRUD Request")
Rel(j, database, "CRUD Request")
Rel(k, database, "CRUD Request")
@enduml