@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title index Event API\n[mos-content-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "index Event API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-content-service)")

Component(event_controller, "Event Controller", "Controller | TypeScript", "Controller for Event Related Function\n(mos-content-service)")
Component(index, "index", "Function | TypeScript", "Main Function for get Event list data\n(mos-content-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, mainMiddleware, "1. Request get Event list data")

Rel_D(mainMiddleware, event_controller, "2. Request get Event list data")
Rel_D(event_controller, index, "3. Request get Event list data")
Rel_D(index, database, "4. Retrieve Event list data")


@enduml