@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title delete Group Bengkel API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "delete Group Bengkel API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification")
    Component(bengkel, "Group Bengkel Controller", "Controller | NodeJs", "Controller for Group Bengkel Function related\n(NodeJs Bengkel API)")

    Component(delete, "delete", "Function | NodeJs", "Function for Delete Group bengkel data Moadmin\n(NodeJs Bengkel API)")
    Component(deletes, "GroupBengkel.delete", "Function | NodeJs", "Function for Delete Group bengkel data Moadmin\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Delete Group bengkel data Moadmin")

Rel(auth_middleware, bengkel, "2. Request Delete Group bengkel data Moadmin")
Rel(bengkel, delete, "3. Request Delete Group bengkel data Moadmin")
Rel(delete, deletes, "4. Delete Group bengkel data Moadmin")
Rel(deletes, database, "5. Delete Group bengkel data Moadmin")

@enduml