@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title deleted Ref Bengkel API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "deleted Ref Bengkel API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification\n(NodeJs Bengkel API)")
    Component(bengkel, "Ref Bengkel Ds Controller", "Controller | NodeJs", "Controller for Ref Bengkel Ds Function related\n(NodeJs Bengkel API)")

    Component(deleted, "deleted", "Function | NodeJs", "Function for Delete Ref Bengkel data\n(NodeJs Bengkel API)")
    Component(deleteds, "RefBengkelDs.deleted", "Function | NodeJs", "Function for Delete Ref Bengkel\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Delete Ref Bengkel Ds data")
Rel(auth_middleware, bengkel, "2. Request Delete Ref Bengkel Ds data")

Rel(bengkel, deleted, "3. Delete Ref Bengkel Dd data")
Rel(deleted, deleteds, "4. Delete Ref Bengkel Ds data")
Rel(deleteds, database, "5. Delete Ref Bengkel Ds data")

@enduml