@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getAllCarModelsbyBrandID API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "getAllCarModelsbyBrandID API\n[Component]"){
    Component(getAllCarModelsbyBrandID, "carModel.getAllCarModelsbyBrandID", "Function | NodeJs", "Function for Get All car model by brand ID\n(NodeJs Bengkel API)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, getAllCarModelsbyBrandID, "1. Request Get All car model data by brand ID")

Rel(getAllCarModelsbyBrandID, database, "2. Get All car model data by brand ID")

@enduml