@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getDetail Notifikasi API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "getDetail Notifikasi API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification")
    Component(bengkel, "Notifikasi Controller", "Controller | NodeJs", "Controller for Notification Function related\n(NodeJs Bengkel API)")

    Component(getDetail, "getDetail", "Function | NodeJs", "Function for Get Notification detail\n(NodeJs Bengkel API)")
    Component(getDetails, "Notifikasi.getDetail", "Function | NodeJs", "Function for Get Notification detail\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Get Notification detail")

Rel(auth_middleware, bengkel, "2. Request Get Notification detail")
Rel(bengkel, getDetail, "3. Request Get Notification detail")
Rel(getDetail, getDetails, "4. Get Notification detail")
Rel(getDetails, database, "5. Get Notification detail")

@enduml