@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getList Notification API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "getList Notification API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification")
    Component(bengkel, "Notifikasi Controller", "Controller | NodeJs", "Controller for Notification Function related\n(NodeJs Bengkel API)")

    Component(getList, "getList", "Function | NodeJs", "Function for Get list notification data\n(NodeJs Bengkel API)")
    Component(getLists, "Notifikasi.getList", "Function | NodeJs", "Function for Get list notification data\n(NodeJs Bengkel API)")
    Component(countList, "Notifikasi.countList", "Function | NodeJs", "Function for Count List Notification data\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Get list notification data")

Rel(auth_middleware, bengkel, "2. Request Get list notification data")
Rel(bengkel, getList, "3. Request Get list notification data")
Rel(getList, getLists, "4. Request Get list notification data")
Rel(getList, countList, "6. Request Count List Notification data")

Rel(getLists, database, "5. Get list notification data")
Rel(countList, database, "7. Count List Notification data")

@enduml