@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getListMissionRegistration API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "getListMissionRegistration API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification\n(NodeJs Bengkel API)")
    Component(bengkel, "Mission Registration Controller", "Controller | NodeJs", "Controller for Mission Registration Function related\n(NodeJs Bengkel API)")

    Component(getListMissionRegistration, "getListMissionRegistration", "Function | NodeJs", "Function for Get List Mission Registration data\n(NodeJs Bengkel API)")
    Component(activeMission, "Mission.activeMission", "Function | NodeJs", "Function for Retrieve Active Mission data\n(NodeJs Bengkel API)")
    Component(countList, "MapMissionBengkel.countList", "Function | NodeJs", "Function for Count list Mission data\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Get List Mission Registration data")
Rel(auth_middleware, bengkel, "2. Request Get List Mission Registration data")

Rel(bengkel, getListMissionRegistration, "3.Request Get List Mission Registration data")
Rel(getListMissionRegistration, activeMission, "4. Request Retrieve Active Mission data")
Rel(getListMissionRegistration, countList, "6. Request Count list Mission data")

Rel(activeMission, database, "5. Retrieve Active Mission data")
Rel(countList, database, "7. Count list Mission data")
@enduml