@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title readByID Bengkel API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "readByID Bengkel API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification\n(NodeJs Bengkel API)")
    Component(bengkel, "Bengkel Workshop Controller", "Controller | NodeJs", "Controller for Bengkel Workshop Function related\n(NodeJs Bengkel API)")

    Component(readByID, "readByID", "Function | NodeJs", "Function for Read bengkel workshop data by ID\n(NodeJs Bengkel API)")
    Component(readByIDs, "Bengkel.readByID", "Function | NodeJs", "Function for Read bengkel workshop data by ID\n(NodeJs Bengkel API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Read bengkel workshop data by ID")
Rel(auth_middleware, bengkel, "2. Request Read bengkel workshop data by ID")
Rel(bengkel, readByID, "3. Request Read bengkel workshop data by ID")
Rel(readByID, readByIDs, "4. Request Read bengkel workshop data by ID")
Rel(readByIDs, database, "5. Read bengkel workshop data by ID")

@enduml