@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title read Bengkel API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "read Bengkel API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification\n(NodeJs Bengkel API)")
    Component(bengkel, "Bengkel Controller", "Controller | NodeJs", "Controller for Moadmin Function related\n(NodeJs Bengkel API)")

    Component(read, "read", "Function | NodeJs", "Function for Read Bengkel data\n(NodeJs Bengkel API)")
    Component(countAll, "countAll", "Function | NodeJs", "Function for Count All Bengkel data\n(NodeJs Bengkel API)")
    Component(reads, "Bengkel.read", "Function | NodeJs", "Function for Read Bengkel data\n(NodeJs Bengkel API)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Read Bengkel data")
Rel(auth_middleware, bengkel, "2. Request Read Bengkel data")
Rel(bengkel, read, "3. Request Read Bengkel data")
Rel(read, countAll, "4. Request Count All Bengkel data")
Rel(read, reads, "6. Read Bengkel data")

Rel(countAll, database, "5. Request Count All Bengkel data")
Rel(reads, database, "7. Read Bengkel data")