@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title updateQuotaByBengkelID API\n[NodeJs Bengkel API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "Moservice.id Main Services for Customer")
Boundary(api, "updateQuotaByBengkelID API\n[Component]"){
    Component(auth_middleware, "validateBengkelId", "Middleware | NodeJs", "Authentication Middleware for Validate Bengkel ID\n(NodeJs Bengkel API)")
    Component(auth_middlewares, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for Verification\n(NodeJs Bengkel API)")
    Component(detail, "Daily Quota Controller", "Controller | NodeJs", "Controller for Daily Quota Function related\n(NodeJs Bengkel API)")
    
    Component(updateQuotaByBengkelID, "updateQuotaByBengkelID", "Function | NodeJs", "Function for Update Daily quota data by Bengkel ID\n(NodeJs Bengkel API)")
    Component(update, "DailyQuota.update", "Function | NodeJs", "Function for Update Daily Quota data\n(NodeJs Bengkel API)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Validate Bengkel ID")
Rel(auth_middleware, auth_middlewares, "2. Request Update Daily quota data by Bengkel ID")
Rel(auth_middlewares, detail, "3. Request Update Daily quota data by Bengkel ID")
Rel(detail, updateQuotaByBengkelID, "4. Request Update Daily quota data by Bengkel ID")

Rel(updateQuotaByBengkelID, update, "5. Update Daily quota data by Bengkel ID")
Rel(update, database, "6. Update Daily quota data")

@enduml