@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title create Banner API\n[NodeJs Content API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")

Boundary(api, "create Banner API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for verification Function\n(NodeJs Content API)")
    Component(content_controller, "Content Banner Controller", "Controller | NodeJs", "Controller for Banner Related Function\n(NodeJs Content API)")
    Component(create, "create", "Function | NodeJs", "Function for Create Banner data\n(NodeJs Content API)")
    Component(creates, "ContentBanner.create", "Function | NodeJs", "Function for Create Banner data\n(NodeJs Content API)")
    Component(insertMapBannerBengkel, "ContentBanner.insertMapBannerBengkel", "Function | NodeJs", "Function for Insert map banner bengkel\n(NodeJs Content API)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Create Banner data")
Rel(auth_middleware, content_controller, "2. Request Create Banner data")
Rel(content_controller, create, "3. Request Create Banner data")
Rel(create, creates, "4. Request Create Banner data")
Rel(create, insertMapBannerBengkel, "6. Request Insert map banner bengkel")

Rel(creates, database, "5. Create Banner data")
Rel(insertMapBannerBengkel, database, "7. Insert map banner bengkel")
@enduml