@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getCategoryByIdMoadmin API\n[NodeJs Content API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")

Boundary(api, "getCategoryByIdMoadmin API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for verification Function\n(NodeJs Content API)")
    Component(content_controller, "Content Category Controller", "Controller | NodeJs", "Controller for Content Category Related Function\n(NodeJs Content API)")
    Component(getCategoryByIdMoadmin, "getCategoryByIdMoadmin", "Function | NodeJs", "Function for Get Category By ID Moadmin\n(NodeJs Content API)")
    Component(getCategoryByIdMoadmins, "ContentCategory.getCategoryByIdMoadmin", "Function | NodeJs", "Function for Get Category By ID Moadmin\n(NodeJs Content API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Get Category By ID Moadmin")
Rel(auth_middleware, content_controller, "2. Request Get Category By ID Moadmin")
Rel(content_controller, getCategoryByIdMoadmin, "3. Request Get Category By ID Moadmin")
Rel(getCategoryByIdMoadmin, getCategoryByIdMoadmins, "4. Request Get Category By ID Moadmin")

Rel(getCategoryByIdMoadmins, database, "5. Create Categories Moadmin")
@enduml