@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title readList Pilihan lain API\n[NodeJs Content API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")

Boundary(api, "readList Pilihan lain API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for verification Function\n(NodeJs Content API)")
    Component(content_controller, "Content Pilihan Lain Controller", "Controller | NodeJs", "Controller for Content Pilihan Lain Related Function\n(NodeJs Content API)")
    Component(readList, "readList", "Function | NodeJs", "Function for Read List Pilihan Lain data\n(NodeJs Content API)")
    Component(readLists, "ContentPilihanLain.readList", "Function | NodeJs", "Function for Read list Pilihan Lain data\n(NodeJs Content API)")
    Component(countList, "ContentPilihanLain.countList", "Function | NodeJs", "Function for Count List Pilihan Lain data\n(NodeJs Content API)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Read list Pilihan Lain data")
Rel(auth_middleware, content_controller, "2. Request Read list Pilihan Lain data")
Rel(content_controller, readList, "3. Request Read list Pilihan Lain data")
Rel(readList, readLists, "4. Request Read list Pilihan Lain data")
Rel(readList, countList, "6. Request Count List Pilihan Lain data")

Rel(readLists, database, "5. Read list Pilihan Lain data")
Rel(countList, database, "7. Count List Pilihan Lain data")

@enduml