@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title deleteByServiceBerkalaID API\n[NodeJs Katalog API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "deleteByServiceBerkalaID API\n[Component]"){
Component(auth_middleware, "user.login", "Function | NodeJs", "Function for login\n(NodeJs Katalog API)")

Component(auth_middlewares, "auth.verify", "Middleware | NodeJs", "Middleware for Verification\n(NodeJs Katalog API)")
Component(reference_controller, "Service Berkala Controller", "Controller | NodeJs", "Controller for Service Berkala Related function\n(NodeJs Katalog API)")
Component(deleteByServiceBerkalaID, "deleteByServiceBerkalaID", "Function | NodeJs", "Function for delete data by service berkala ID\n(NodeJs Katalog API)")
Component(delete, "ServiceBerkala.delete", "Function | NodeJs", "Function for delete data by service berkala ID\n(NodeJs Katalog API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request delete service berkala data by service berkala ID")
Rel_D(auth_middleware, auth_middlewares, "2. Request delete service berkala data by service berkala ID")
Rel_D(auth_middlewares, reference_controller, "3. Request delete service berkala data by service berkala ID")
Rel_D(reference_controller, deleteByServiceBerkalaID, "4. Request delete service berkala data by service berkala ID")
Rel_D(deleteByServiceBerkalaID, delete, "5. Request delete service berkala data by service berkala ID with items")
Rel_D(delete, database, "6. Delete service berkala data by service berkala ID with Items")

@enduml