@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getServiceUmumByBengkelIDApp Service Umum API\n[NodeJs Katalog API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "getServiceUmumByBengkelIDApp Service Umum API\n[Component]"){
Component(auth_middleware, "user.login", "Function | NodeJs", "Function for login\n(NodeJs Katalog API)")

Component(auth_middlewares, "auth.verify", "Middleware | NodeJs", "Middleware for Verification\n(NodeJs Katalog API)")
Component(reference_controller, "Service Umum Controller", "Controller | NodeJs", "Controller for Service Umum Related function\n(NodeJs Katalog API)")
Component(getServiceUmumByBengkelIDApp, "getServiceUmumByBengkelIDApp", "Function | NodeJs", "Function for get Service Umum By Bengkel ID App\n(NodeJs Katalog API)")
Component(getServiceUmumByBengkelID, "ServiceUmum.getServiceUmumByBengkelID", "Function | NodeJs", "Function for get Service Umum By Bengkel ID\n(NodeJs Katalog API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request get Service Umum By Bengkel ID App")
Rel_D(auth_middleware, auth_middlewares, "2. Request get Service Umum By Bengkel ID App")
Rel_D(auth_middlewares, reference_controller, "3. Request get Service Umum By Bengkel ID App")
Rel_D(reference_controller, getServiceUmumByBengkelIDApp, "4. Get Service Umum By Bengkel ID App")
Rel_D(getServiceUmumByBengkelIDApp, getServiceUmumByBengkelID, "5. Request Get Service Umum By Bengkel ID")
Rel_D(getServiceUmumByBengkelID, database, "6. Get Service Umum By Bengkel ID")

@enduml