@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title get Service Reminder Config API\n[NodeJs Katalog API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "get Service Reminder Config API\n[Component]"){
Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Middleware for Verification\n(NodeJs Katalog API)")
Component(reference_controller, "Service Reminder Config Controller", "Controller | NodeJs", "Controller for Service Reminder Config Related function\n(NodeJs Katalog API)")
Component(get, "get", "Function | NodeJs", "Function for get Service Reminder Config\n(NodeJs Katalog API)")
Component(gets, "ServiceReminderConfig.get", "Function | NodeJs", "Function for get by ID\n(NodeJs Katalog API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request get Service Reminder Config")
Rel_D(auth_middleware, reference_controller, "2. Request get Service Reminder Config")

Rel_D(reference_controller, get, "3. Request Get Service Reminder Config")
Rel_D(get, gets, "4. Get Service Reminder Config")

Rel_D(gets, database, "5. Get Service Reminder Config")

@enduml