@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title readByBengkelID Service Umum API\n[NodeJs Katalog API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "readByBengkelID Service Umum API\n[Component]"){
Component(auth_middleware, "user.login", "Function | NodeJs", "Function for login\n(NodeJs Katalog API)")

Component(auth_middlewares, "auth.verify", "Middleware | NodeJs", "Middleware for Verification\n(NodeJs Katalog API)")
Component(reference_controller, "Service Umum Controller", "Controller | NodeJs", "Controller for Service Umum Related function\n(NodeJs Katalog API)")
Component(readByBengkelID, "readByBengkelID", "Function | NodeJs", "Function for read service umum data by bengkel ID\n(NodeJs Katalog API)")
Component(read, "ServiceUmum.read", "Function | NodeJs", "Function for read service umum data\n(NodeJs Katalog API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request read service umum data by bengkel ID")
Rel_D(auth_middleware, auth_middlewares, "2. Request read service umum data by bengkel ID")
Rel_D(auth_middlewares, reference_controller, "3. Request read service umum data by bengkel ID")
Rel_D(reference_controller, readByBengkelID, "4. Read service umum data by bengkel ID")
Rel_D(readByBengkelID, read, "5. Request read service umum data")
Rel_D(read, database, "6. Read service umum data")

@enduml