@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title update Service Reminder Config API\n[NodeJs Katalog API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "update Service Reminder Config API\n[Component]"){
Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Middleware for Verification\n(NodeJs Katalog API)")
Component(reference_controller, "Service Reminder Config Controller", "Controller | NodeJs", "Controller for Service Reminder Config Related function\n(NodeJs Katalog API)")
Component(update, "update", "Function | NodeJs", "Function for update Service Reminder Config\n(NodeJs Katalog API)")
Component(findById, "ServiceReminderConfig.findById", "Function | NodeJs", "Function for find by ID\n(NodeJs Katalog API)")
Component(updateById, "updateById", "Function | NodeJs", "Function for update Service Reminder Config by ID\n(NodeJs Katalog API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request update Service Reminder Config")
Rel_D(auth_middleware, reference_controller, "2. Request update Service Reminder Config")

Rel_D(reference_controller, update, "3. Request update Service Reminder Config")
Rel_D(update, findById, "4. Find Service Reminder Config by ID")
Rel_D(update, updateById, "6. Update Service Reminder Config by ID")
Rel_D(updateById, database, "7. Update Service Reminder Config by ID")
Rel_D(findById, database, "5. Find Service Reminder Config by ID")

@enduml