@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Forgot Password\n[forgotPassword]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")
    
    Boundary(api, "forgotPassword API\n[Component]"){
        
        Boundary(middleware, "middleware user API\n[Component]"){

            Component(check_limiter, "forgotPasswordLimiter", "Middleware | NodeJS", "Middleware for check request limiter (max 3 attempts in 5 minutes)\n{ms-auth}")
            Component(auth_middleware, "verifyForgotPasswordUser", "Middleware | NodeJS", "Middleware for check request body\n{ms-auth}")

        }
        
        ' Boundary(account_creation, "account_creation\n[Component]"){

        '     Component(checkEmailExist, "checkEmailExist", "Middleware | NodeJS", "Function for Check if Email is Exist\n{ms-auth}")

        ' }

        Component(forgotPassword, "forgotPassword", "Function | NodeJS", "API for send email forgot password user\n{ms-auth}")

        Boundary(sendEmail, "send_email\n[Component]"){

            Component(sendEmailForgotPassword, "sendEmailForgotPassword", "Function | NodeJS", "Function for Send Email Forgot Password\n{ms-auth}")

        }
    }
    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")

    AddProperty("URL", "`${process.env.OTP_URL}/pin?ncNeeded=true`")
    AddProperty("headers", "'Authorization': `App ${process.env.OTP_AUTH}`, 'Content-Type': 'application/json'")
    System_Ext(infobip, "InfoBip", "External System for send message otp")


Rel_D(web_momo_x, check_limiter, "1. Check limiter request")
Rel_D(check_limiter, auth_middleware, "2. Send request check body request")
Rel_D(auth_middleware, forgotPassword, "3. Request send email forgot password")
Rel_D(forgotPassword, momo_x_storage, "4. Check user email / phone number")

' if forgot passwrod with email
Rel_D(forgotPassword, momo_x_storage, "5A. (If user forgot password with email) Upsert OTP forgot password")
Rel_D(forgotPassword, momo_x_storage, "6A. Create Log forgot password")
Rel_R(forgotPassword, sendEmailForgotPassword, "7A. Send email code forgot password")

' if forgot password with phone
Rel_R(forgotPassword, infobip, "5B. (If user forgot password with phone number) Send message PIN forgot password")
Rel_D(forgotPassword, momo_x_storage, "6B. Create Log forgot password")

SHOW_LEGEND()
@enduml