@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Login User\n[registerGoogle]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services")
    
    Boundary(api, "login user API\n[Component]"){

        Boundary(middleware, "middleware user API\n[Component]"){

            Component(auth_middleware, "verifyLoginUser", "Middleware | NodeJS", "Middleware for check request body login user\n{ms-auth}")

        }

        Boundary(account_creation, "account_creation\n[Component]", "lib/account_creation.js"){

            Component(validatePassword, "validatePassword", "Function | NodeJS", "function for check validate password \n{ms-auth}")
            Component(validatePasswordHash, "validatePasswordHash", "Function | NodeJS", "function for check validate password in hash \n{ms-auth}")

        }

        Component(login, "login", "Function | NodeJS", "API for login user\n{ms-auth}")

    }

    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware, "1. Send request login user")
Rel_D(auth_middleware, validatePassword, "2. Send request validate password")
Rel_R(auth_middleware, login, "3. Send request login user")
Rel_D(login, momo_x_storage, "4. check email / phone")
Rel_D(login, validatePasswordHash, "5. validate password hash")
Rel_D(login, momo_x_storage, "6. Insert session login user")
Rel_D(login, momo_x_storage, "7. Insert log login user")

SHOW_LEGEND()
@enduml