@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Logout User\n[logout]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services")
    
    Boundary(api, "logout API\n[Component]"){

        Boundary(middleware, "middleware user API\n[Component]"){

            Component(auth_middleware_1, "verifyUserHeaderToken", "Middleware | NodeJS", "Middleware for check header token\n{ms-auth}")
            Component(auth_middleware_2, "verifyLogoutUser", "Middleware | NodeJS", "Middleware for check request body\n{ms-auth}")

        }

        Component(logout, "logout", "Function | NodeJS", "API for logout user\n{ms-auth}")

    }

    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware_1, "1. Send request check header token")
Rel_D(web_momo_x, auth_middleware_2, "2. Send request check request body auth_id")
Rel_D(auth_middleware_1, logout,  "3. Send request logout")
Rel_D(auth_middleware_2, logout, "3. Send request logout")
Rel_D(logout, momo_x_storage, "4. Update session expired to now")
Rel_D(logout, momo_x_storage, "5. Insert log logout user")

SHOW_LEGEND()
@enduml