@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Register User\n[register]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services")
    
    Boundary(api, "register user API\n[Component]"){

        Boundary(middleware, "middleware user API\n[Component]"){

            Component(auth_middleware, "verifyRegisterUser", "Middleware | NodeJS", "Middleware for check request body register user\n{ms-auth}")

        }

        Boundary(account_creation, "account_creation\n[Component]", "lib/account_creation.js"){

            Component(validatePassword, "validatePassword", "Function | NodeJS", "function for validate password \n{ms-auth}")
            Component(checkEmailExist, "checkEmailExist", "Function | NodeJS", "function for check email exist \n{ms-auth}")
            Component(checkPhoneExist, "checkPhoneExist", "Function | NodeJS", "function for check phone exist \n{ms-auth}")
            Component(encryptPassword, "encryptPassword", "Function | NodeJS", "function for encryipt password user \n{ms-auth}")

        }

        Component(register, "register", "Function | NodeJS", "API for register user\n{ms-auth}")

    }

    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware, "1. Send request check Email and check request body")
Rel_D(auth_middleware, validatePassword, "2. Send request check validate password")
Rel_D(auth_middleware, checkEmailExist, "3. Send request check email")
Rel_D(auth_middleware, checkPhoneExist, "4. Send request check phone number")
Rel_D(checkPhoneExist, momo_x_storage, "5. Check phone number")
Rel_D(checkEmailExist, momo_x_storage, "6. Check email")
Rel_D(auth_middleware, register, "7. Send request register user")
Rel_D(register, encryptPassword, "8. Encrypt password user")
Rel_D(register, momo_x_storage, "8. Create new user")
Rel_D(register, momo_x_storage, "9. Insert log register user")

SHOW_LEGEND()
@enduml