@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Forgot Password\n[forgotPassword]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")
    
    Boundary(api, "forgotPassword API\n[Component]"){
        
        Boundary(middleware, "middleware user API\n[Component]"){

            Component(auth_middleware, "verifyResendForgotPasswordCodeUser", "Middleware | NodeJS", "Middleware for check request body\n{ms-auth}")

        }

        Component(forgotPassword, "forgotPassword", "Function | NodeJS", "API for send email forgot password user\n{ms-auth}")

        Boundary(sendEmail, "send_email\n[Component]"){

            Component(sendEmailForgotPassword, "sendEmailForgotPassword", "Function | NodeJS", "Function for Send Email Forgot Password\n{ms-auth}")

        }
    }
    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")

    AddProperty("URL", "`${process.env.OTP_URL}/pin?ncNeeded=true`")
    AddProperty("headers", "'Authorization': `App ${process.env.OTP_AUTH}`, 'Content-Type': 'application/json'")
    System_Ext(infobip, "InfoBip", "External System for send message otp")


Rel_D(web_momo_x, auth_middleware, "1. Check limiter request")
Rel_D(auth_middleware, forgotPassword, "2. Request send email forgot password")
Rel_D(forgotPassword, momo_x_storage, "3. Check user email / phone number")

' if forgot passwrod with email
Rel_D(forgotPassword, momo_x_storage, "4A. (If user forgot password with email) Upsert OTP forgot password")
Rel_D(forgotPassword, momo_x_storage, "5A. Create Log resend forgot password")
Rel_R(forgotPassword, sendEmailForgotPassword, "6A. Send email resend code forgot password")

' if forgot password with phone
Rel_R(forgotPassword, infobip, "4B. (If user forgot password with phone number) Send message PIN forgot password")
Rel_D(forgotPassword, momo_x_storage, "5B. Create Log resend forgot password")

SHOW_LEGEND()
@enduml