@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title Component Diagram for Get New Insurance\n (api/v1/insurance/new-inquiry)
Container(adiraku, "Adiraku", "Application | Angular & React Native", "The main interface that the customer interacts with Adiraku")

Boundary(api, "Get New Insurance API\n[Component]"){
    Component(middleware, "verifyTokenV2", "Middleware | Function", "Middleware for Verify Token")

    AddProperty("Path", "ms-insurance\api\v1\insurance\controller.js")
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller for Insurance Related Function")

    Component(getNewInsurance, "getNewInsurance", "Function | NodeJs", "Function for Get New Insurance data")
    
    Component(checkDataInsuranceV2, "utils.checkDataInsuranceV2", "Function | NodeJs", "Function for Check data Insurance V2")
    
}
    AddProperty("URL", "/api/v1/account/find-account-by-id")
    AddProperty("Repository", "ms-account")
    Component(findAccountByid, "findAccountByid", "Function | NodeJs", "Function for Get user data information by ID")
    
    AddProperty("URL", "/api/v1/account/contract-list")
    AddProperty("Repository", "ms-account")
    Component(getContractList, "getContractList", "Function | NodeJs", "Function for Get data Contract List")

ContainerDb(database, "Adiraku Storage", "mySql Database", "dataContract.data.map")

ContainerDb(Redis, "Adiraku Storage", "Redis Database", "Data Redis")

Rel(adiraku, middleware, "1. API CALL & Verify Token")
Rel(middleware, controller, "2. Request Get New Insurance data")
Rel(controller, getNewInsurance, "3. Request Get New Insurance data")
Rel(getNewInsurance, findAccountByid, "4. Get user data information by ID")
Rel(getNewInsurance, getContractList, "5. Get data Contract List")

Rel_R(getNewInsurance, database, "6. Get insurance by ID")
Rel(getNewInsurance, checkDataInsuranceV2, "7. Request Check Data Insurance")
Rel(checkDataInsuranceV2, Redis, "8. Check Data Insurance")



@enduml