@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title index province API\n[mos-bengkel-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "index province API\n[Component]"){
Component(province_controller, "Province Controller", "Controller | TypeScript", "Controller for Province Related Function\n(mos-bengkel-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-bengkel-service)")
Component(index, "index", "Function | TypeScript", "Main Function for Show All Provinces data\n(mos-bengkel-service)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, mainMiddleware, "1. Request Show All Provinces data")

Rel_D(mainMiddleware, province_controller, "2. Request Show All Provinces data")
Rel_D(province_controller, index, "3. Request Show All Provinces data")
Rel_D(index, database, "4. Retrieve Provinces data")

@enduml