@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title uploadImage API\n[mos-bengkel-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "uploadImage API\n[Component]"){
Component(mission_controller, "Mission Controller", "Controller | TypeScript", "Controller for Mission Related Function\n(mos-bengkel-service)")
Component(auth_operator_middleware, "Auth Operator Middleware", "Middleware | TypeScript", "Middleware for Authentication\n(mos-bengkel-service)")
Component(multerMiddleware, "Multer Middleware", "Middleware | TypeScript", "Middleware for Uploading Files\n(mos-bengkel-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-bengkel-service)")
Component(uploadImage, "uploadImage", "Function | TypeScript", "Main Function for Upload Image data\n(mos-bengkel-service)")
Component(uploadCloudinary, "uploadCloudinary", "Function | TypeScript", "Function for Upload image to Cloudinary\n(mos-bengkel-service)")
Component(updateMission, "MissionRepository.update", "Function | TypeScript", "Function for Update Mission data\n(mos-bengkel-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
AddProperty("URL", "https://res.cloudinary.com/adiramoservice/q_auto,f_auto/v1/${cloudinaryConfig.cloudinary_path}")
System_Ext(cloudinary, "Cloudinary", "External for store Image data")

Rel_D(Web_Moservice, mainMiddleware, "1. Request Upload Image")

Rel_D(mainMiddleware, auth_operator_middleware, "2. Request Upload Image")
Rel_D(auth_operator_middleware, multerMiddleware, "3. Request Upload Image")
Rel_D(multerMiddleware, mission_controller, "4. Request Upload Image")
Rel_D(mission_controller, uploadImage, "5. Request Upload Image")
Rel_D(uploadImage, uploadCloudinary, "6. Upload Image")
Rel_R(uploadImage, updateMission, "8. Update Image data")
Rel_R(updateMission, database, "9.Upload Image data")
Rel_L(uploadCloudinary, cloudinary, "7.Upload Image to Cloudinary")

@enduml