@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for update va (api/v1/account/balance/va)

'AddProperty("repository", "MS-Authentication")
'AddProperty("url", "/api/v1/auth/logout")
'Container(anonymous, "Logout API", "Microservices | NodeJS", "Logout Adiraku for Nasabah")

System_Boundary(getAccountBy, "Check Account API") {
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller")
}

ContainerDb(database, "Adiraku Storage", "mysql", "adr_account, adr_va, adr_va_transactions")

Rel(anonymous, controller, 1. API Call [JSON/HTTPS])
Rel(controller, database, 2. get data adr_va)
Rel(controller, database, 3. get data adr_account)
Rel(controller, database, 4. update data va)
Rel(controller, database, 5. insert data va transactions)

SHOW_LEGEND()

@enduml
