@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Update VA (api/v1/account/post-va-by)

'AddProperty("repository", "MS-Authentication")
'AddProperty("url", "/api/v1/auth/logout")
'Container(anonymous, "Logout API", "Microservices | NodeJS", "Logout Adiraku for Nasabah")

System_Boundary(getAccountBy, "Check Account API") {
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller")
}

ContainerDb(database, "Adiraku Storage", "mysql", "adr_va")

Rel(anonymous, controller, 1. API Call [JSON/HTTPS])
Rel(controller, database, 2. update data adr_va)

SHOW_LEGEND()

@enduml
