@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Change Password Customer\n[changePassword]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")
    
    Boundary(api, "changePassword API\n[Component]"){

        Component(auth_middleware, "verifyChangePassword", "Middleware | NodeJS", "Middleware for check request body API changePassword\n{ms-auth}")
        Component(changePassword, "changePassword", "Function | NodeJS", "API validate data changePassword \n{ms-auth}")

    }
    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware, "1. Send request changePassword customer and check request body")
Rel_R(auth_middleware, changePassword, "2. Request changePassword and send request body")
Rel_D(changePassword, momo_x_storage, "3. Check email & password customer")
Rel_D(changePassword, momo_x_storage, "3. Update password customer")
Rel_D(changePassword, momo_x_storage, "4. Insert log changePassword customer")

SHOW_LEGEND()
@enduml