@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Check Forgot Password Code Customer\n[checkForgotPasswordCode]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")
    
    Boundary(api, "checkForgotPasswordCode API\n[Component]"){

        Component(auth_middleware, "verifyForgotPasswordCode", "Middleware | NodeJS", "Middleware for check request body API checkForgotPasswordCode\n{ms-auth}")
        Component(checkForgotPasswordCode, "checkForgotPasswordCode", "Function | NodeJS", "API for check forgot password code customer\n{ms-auth}")

    }

    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware, "1. Send request check forgot password code and check request body")
Rel_R(auth_middleware, checkForgotPasswordCode, "2. Request check forgot password code and send request body")
Rel_D(checkForgotPasswordCode, momo_x_storage, "3. Check otp from request")
Rel_D(checkForgotPasswordCode, momo_x_storage, "4. Update otp status")

SHOW_LEGEND()
@enduml