@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Forgot Password Customer\n[forgotPassword]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")
    
    Boundary(api, "forgotPassword API\n[Component]"){

        Component(auth_middleware, "verifyForgotPasswordAndRefreshOTP", "Middleware | NodeJS", "Middleware for check request body API forgotPassword\n{ms-auth}")
        Component(forgotPassword, "forgotPassword", "Function | NodeJS", "API for forgot password customer\n{ms-auth}")


        Boundary(boundarySendEmailForgotPassword, "sendEmailForgotPassword\n[Component]", "lib/email/models/forgotPassword.js"){
            Component(sendEmailForgotPassword, "sendEmailForgotPassword", "Function | NodeJS", "Function for send email code forgot password to customer\n{ms-auth}")
        }

    }


    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware, "1. Send request forgot password customer and check request body")
Rel_R(auth_middleware, forgotPassword, "2. Request forgot password and send request body")
Rel_D(forgotPassword, momo_x_storage, "3. Check email customer")
Rel_D(forgotPassword, momo_x_storage, "4. Insert data otp & log customer")
Rel_D(forgotPassword, sendEmailForgotPassword, "5. Send param email, name, & code forgot password. Request send email")

SHOW_LEGEND()
@enduml