@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Login Customer via Gmail\n[loginUserViaGmail]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")
    
    Boundary(api, "loginUserViaGmail API\n[Component]"){

        Component(auth_middleware, "verifyLoginUserViaEmail", "Middleware | NodeJS", "Middleware for check request body API loginUserViaGmail\n{ms-auth}")
        Component(loginUserViaGmail, "loginUserViaGmail", "Function | NodeJS", "API validate data loginUserViaGmail \n{ms-auth}")

    }
    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware, "1. Send request loginUserViaGmail customer and check request body")
Rel_R(auth_middleware, loginUserViaGmail, "2. Request loginUserViaGmail and send request body")
Rel_D(loginUserViaGmail, momo_x_storage, "3. Check email google customer")
Rel_D(loginUserViaGmail, momo_x_storage, "4. Insert session & log loginUserViaGmail")

SHOW_LEGEND()
@enduml