@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Reset Password Customer\n[resetPasswordCustomer]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")
    
    Boundary(api, "resetPasswordCustomer API\n[Component]"){

        Component(auth_middleware, "verifyResetPasswordCustomer", "Middleware | NodeJS", "Middleware for check request body API resetPasswordCustomer\n{ms-auth}")
        Component(resetPasswordCustomer, "resetPasswordCustomer", "Function | NodeJS", "API for change password customer from forgot password\n{ms-auth}")

    }

    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware, "1. Send request check forgot password code and check request body")
Rel_R(auth_middleware, resetPasswordCustomer, "2. Request check forgot password code and send request body")
Rel_D(resetPasswordCustomer, momo_x_storage, "3. Check email customer")
Rel_D(resetPasswordCustomer, momo_x_storage, "4. Update password customer")
Rel_D(resetPasswordCustomer, momo_x_storage, "5. Insert log reset password customer")

SHOW_LEGEND()
@enduml