@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title API System\n[mos-user-service]
Component(Web_Moservice, "API Gateway", "Services | TypeScript", "All API used by moservice.id")
Component(API, "mos-user-service", "Repository | TypeScript", "Repository for User Function Related")
Boundary(api, "API System\n[mos-user-service]"){
Component(user, "User", "Function | TypeScript", "Main Function for Inquiry, Create, Update, Delete user data\n(mos-user-service)")
Component(users, "User Bengkel", "Function | TypeScript", "Main Function for Show, Create, Update, Delete User Bengkel data\n(mos-user-service)")
Component(admin, "Admin", "Function | TypeScript", "Main Function for Register, Delete, Update Admin data\n(mos-user-service)")
Component(SpNotif, "SP Notif", "Function | TypeScript", "Main Function for Inquiry, Show, Create, Delete, Update SP Notif data\n(mos-user-service)")
Component(OTP, "OTP Request", "Function | TypeScript", "Main Function for Inquiry, Create, OTP Request\n(mos-user-service)")
Component(FindUser, "Find User", "Function | TypeScript", "Main Function for Find user Attribute, Find user By ID, Find User Vehicle, Find User Vehicle by ID\n(mos-user-service)")
Component(FindAdmin, "Find Admin", "Function | TypeScript", "Main Function for Find Role, Find Admin By ID, Find All Admin\n(mos-user-service)")
Component(Password, "Password", "Function | TypeScript", "Main Function for Forgot Password Operator, Forget Password User, Change Password\n(mos-user-service)")
Component(RateReview, "Rate Review", "Function | TypeScript", "Main Function for retrieve Rate Review data, Rate review data by ID, Update Rate Review data\n(mos-user-service)")
Component(Profile, "Profile", "Function | TypeScript", "Main Function for Upload, Delete Profile Picture, Update Profile User\n(mos-user-service)")
Component(BengkelRating, "Bengkel Rating", "Function | TypeScript", "Main Function for Retrieve Bengkel Rating data\n(mos-user-service)")
Component(BookingCust, "Booking Customer", "Function | TypeScript", "Main Function for Retrieve Booking Customer data\n(mos-user-service)")
Component(Vehicle, "User Vehicle", "Function | TypeScript", "Main Function for Save User Vehicle, Delete User Vehicle, Update Primary Vehicle data\n(mos-user-service)")
Component(Credential, "Credential", "Function | TypeScript", "Main Function for Get user Credential data, Check Email or Phone data\n(mos-user-service)")
Component(Message, "Message", "Function | TypeScript", "Main Function for Inbox, Find Message By ID, Send Email Message\n(mos-user-service)")
Component(Moadmin, "Index User Moadmin", "Function | TypeScript", "Function for Inquiry User Moadmin data\n(mos-user-service)")
Component(CheckUser, "Index Check User", "Function | TypeScript", "Function for Check User data\n(mos-user-service)")
Component(Login, "Login", "Function | TypeScript", "Function for Login\n(mos-user-service)")
Component(Logout, "Logout", "Function | TypeScript", "Function for Logout\n(mos-user-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, API, "Request use function related to User")

Rel_D(API, user, "Request Inquiry, Create, Update, Delete user data")
Rel_D(API, users, "Request Show, Create, Update, Delete User Bengkel data")
Rel_D(API, admin, "Request Register, Delete, Update Admin data")
Rel_D(API, SpNotif, "Request Inquiry, Show, Create, Delete, Update SP Notif data")
Rel_D(API, OTP, "Request Inquiry, Create, OTP Request")
Rel_D(API, FindUser, "Request Find user Attribute, Find user By ID, Find User Vehicle, Find User Vehicle by ID")
Rel_D(API, FindAdmin, "Request Find Role, Find Admin By ID, Find All Admin")
Rel_D(API, Password, "Request Forgot Password Operator, Forget Password User, Change Password")
Rel_D(API, RateReview, "Request Retrieve Rate Review data, Rate review data by ID, Update Rate Review data")
Rel_D(API, Profile, "Request Upload, Delete Profile Picture, Update Profile User")
Rel_D(API, BengkelRating, "Request Retrieve Bengkel Rating data")
Rel_D(API, BookingCust, "Request Retrieve Booking Customer data")
Rel_D(API, Vehicle, "Request Save User Vehicle, Delete User Vehicle, Update Primary Vehicle data")
Rel_D(API, Credential, "Request Get user Credential data, Check Email or Phone data")
Rel_D(API, Message, "Request Inbox, Find Message By ID, Send Email Message")
Rel_D(API, Moadmin, "Request Inquiry User Moadmin data")
Rel_D(API, CheckUser, "Request Check User data")
Rel_D(API, Login, "Request Login")
Rel_D(API, Logout, "Request Logout")

Rel_D(user, database, "Inquiry, Create, Update, Delete user data")
Rel_D(users, database, "Show, Create, Update, Delete User Bengkel data")
Rel_D(admin, database, "Register, Delete, Update Admin data")
Rel_D(SpNotif, database, "Inquiry, Show, Create, Delete, Update SP Notif data")
Rel_D(OTP, database, "Inquiry, Create, OTP Request")
Rel_D(FindUser, database, "Find user Attribute, Find user By ID, Find User Vehicle, Find User Vehicle by ID")
Rel_D(FindAdmin, database, "Find Role, Find Admin By ID, Find All Admin")
Rel_D(Password, database, "Forgot Password Operator, Forget Password User, Change Password")
Rel_D(RateReview, database, "Retrieve Rate Review data, Rate review data by ID, Update Rate Review data")
Rel_D(Profile, database, "Upload, Delete Profile Picture, Update Profile User")
Rel_D(BengkelRating, database, "Retrieve Bengkel Rating data")
Rel_D(BookingCust, database, "Retrieve Booking Customer data")
Rel_D(Vehicle, database, "Save User Vehicle, Delete User Vehicle, Update Primary Vehicle data")
Rel_D(Credential, database, "Get user Credential data, Check Email or Phone data")
Rel_D(Message, database, "Inbox, Find Message By ID, Send Email Message")
Rel_D(Moadmin, database, "Inquiry User Moadmin data")
Rel_D(CheckUser, database, "Check User data")
Rel_D(Login, database, "Login")
Rel_D(Logout, database, "Logout")