@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title destroy sp notif API\n[mos-user-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "destroy sp notif API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-user-service)")
Component(sp_moadmin_auth_middleware, "SP Moadmin Auth Middleware", "Middleware | TypeScript", "Middleware for Moadmin Authentication\n(mos-user-service)")
Component(sp_notif_controller, "SP Notif Controller", "Controller | TypeScript", "Controller for SP Notification Related Function\n(mos-user-service)")
Component(destroy, "destroy", "Function | TypeScript", "Function for delete notification data by id\n(mos-user-service)")
Component(destroys, "MoadminNotifRepository.update", "Function | TypeScript", "Function for delete notification data by id\n(mos-user-service)")


}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, mainMiddleware, "1. Request delete notification data")

Rel_D(mainMiddleware, sp_moadmin_auth_middleware, "2. Request delete notification data")
Rel_D(sp_moadmin_auth_middleware, sp_notif_controller, "3. Request delete notification data")
Rel_D(sp_notif_controller, destroy, "4. Delete notification data")
Rel_D(destroy, destroys, "5. Request Update notification data")

Rel_D(destroys, database, "6. Update notification data")

@enduml