@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title forgotPassword API\n[mos-user-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "forgotPassword API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-user-service)")
Component(user_controller, "User Controller", "Controller | TypeScript", "Controller for User Related Function\n(mos-user-service)")
Component(forgotPassword, "forgotPassword", "Function | TypeScript", "Function for forgot password\n(mos-user-service)")
Component(forgotPasswords, "CredentialRepository.update", "Function | TypeScript", "Function for update credential data\n(mos-user-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")


Rel(Web_Moservice, mainMiddleware, "1. Request forgot password")

Rel(mainMiddleware, user_controller, "2. Request forgot password")
Rel(user_controller, forgotPassword, "3. Forgot password")
Rel(forgotPassword, forgotPasswords, "4. Update credential data")

Rel_D(forgotPasswords, database, "5. Update credential data")

@enduml