@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title forgotPasswordOperator API\n[mos-user-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "forgotPasswordOperator API\n[Component]"){
Component(operators_controller, "Operators Controller", "Controller | TypeScript", "Controller for Operator Related Function\n(mos-user-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-user-service)")
Component(forgotPasswordOperator, "forgotPasswordOperator", "Function | TypeScript", "Function for forgot password for operator user\n(mos-user-service)")
Component(checkUserOperatorOTP, "MstOtpRepository.count", "Function | TypeScript", "Function for Check User Operator\n(mos-user-service)")
Component(operators, "MstOperatorRepository.findOne", "Function | TypeScript", "Function for retrieve Operator data\n(mos-user-service)")
Component(checkNewPasswordWithOldPassword, "checkNewPasswordWithOldPassword", "Function | TypeScript", "Function for compare new password with old password\n(mos-user-service)")
Component(updatePassword, "MstOperatorRepository.update", "Function | TypeScript", "Function for Update Password\n(mos-user-service)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, mainMiddleware, "1. Operator Forgot Password")

Rel_D(mainMiddleware, operators_controller, "2. Operator Forgot Password")
Rel(operators_controller, forgotPasswordOperator, "3. Operator Forgot Password")

Rel(forgotPasswordOperator, checkUserOperatorOTP, "4. Check User Operator OTP")
Rel(checkUserOperatorOTP, database, "5. Check User Operator OTP")

Rel(forgotPasswordOperator, operators, "6. Check Operator data")
Rel(operators, database, "7. Retrieve Operator data")

Rel(forgotPasswordOperator, checkNewPasswordWithOldPassword, "8. Compare New Pass & Old Pass")
Rel(forgotPasswordOperator, updatePassword, "9. Update Password")
Rel(updatePassword, database, "10.Update Password")

@enduml