@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title updatedAdmin API\n[mos-user-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "updatedAdmin API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-user-service)")

Component(operators_controller, "Operators Controller", "Controller | TypeScript", "Controller for Operator Related Function\n(mos-user-service)")
Component(updatedAdmin, "updatedAdmin", "Function | TypeScript", "Function for update admin data\n(mos-user-service)")
Component(updatedAdmins, "MstOperatorRepository.update", "Function | TypeScript", "Function for update admin data\n(mos-user-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel(Web_Moservice, mainMiddleware, "1. Request update admin data")

Rel(mainMiddleware, operators_controller, "2. Request update admin data")
Rel(operators_controller, updatedAdmin, "3. Find update admin data")
Rel_D(updatedAdmin, updatedAdmins, "4. Update admin data")
Rel_D(updatedAdmins, database, "5. Update admin data")

@enduml