@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Get Car Model API\n[getCarModel]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")

    Boundary(middleware, "middleware user API\n[Component]"){

       Component(validate_query, "validateRequestQuery", "Middleware | NodeJS", "Middleware for validate query\n{ms-catalog}")

    }
    
    Boundary(api, "getCarModel API\n[Component]"){

        Component(getCarModel, "getCarModel", "Function | NodeJS", "API for get data model car\n{ms-catalog}")

    }
    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for catalog momo x")


Rel_D(web_momo_x, validate_query, "1. Validate request query")
Rel_D(validate_query, getCarModel, "2. Request get data car model")
Rel_D(getCarModel, momo_x_storage, "3. Get data car model")

SHOW_LEGEND()
@enduml