@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title NodeJs Service Platform Katalog API

Component(Web_Moservice, "API Gateway", "Services | TypeScript", "All API used by moservice.id")
Component(API, "NodeJs Service Platform Katalog API", "Repository | NodeJs", "Repository for NodeJs Katalog Related Function")

Boundary(api, "NodeJs Booking API\n[Component]"){
Component(bookingGetBrandList, "bookingGetBrandList", "Function | NodeJs", "Function for Get booking brand list\n(NodeJs Katalog API)")
Component(bookingGetCarModelList, "bookingGetCarModelList", "Function | NodeJs", "Function for Get booking car model list\n(NodeJs Katalog API)")
Component(createByBengkelID, "createByBengkelID", "Function | NodeJs", "Function for Create service berkala data by bengkel ID\n(NodeJs Katalog API)")
Component(createItemByCategoryID, "createItemByCategoryID", "Function | NodeJs", "Function for Create Item By Category ID\n(NodeJs Katalog API)")
Component(create, "Create Service", "Function | NodeJs", "Function for Create Service Berkala & Reminder data\n(NodeJs Katalog API)")
Component(delete, "Delete Service", "Function | NodeJs", "Function for Delete Service Reminder Config, Delete Service Berkala by ID, Delete Service Umum by ID\n(NodeJs Katalog API)")
Component(getAllParam, "getAllParam", "Function | NodeJs", "Function for Get all mobil param\n(NodeJs Katalog API)")
Component(getAllServiceItemAndCategory, "getAllServiceItemAndCategory", "Function | NodeJs", "Function for Get all service item and category\n(NodeJs Katalog API)")
Component(getBrandList, "getBrandList", "Function | NodeJs", "Function for Get brand list\n(NodeJs Katalog API)")
Component(getModelList, "getModelList", "Function | NodeJs", "Function for Get model list\n(NodeJs Katalog API)")
Component(getRefTipeServis, "getRefTipeServis", "Function | NodeJs", "Function for Get tipe servis data\n(NodeJs Katalog API)")

Component(getServiceBerkalaForBookingByBengkelIDApp, "getServiceBerkalaForBookingByBengkelIDApp", "Function | NodeJs", "Function for Get Service Berkala For Booking By Bengkel ID\n(NodeJs Katalog API)")
Component(getServiceBerkalaKMList, "getServiceBerkalaKMList", "Function | NodeJs", "Function for Get service berkala KM list\n(NodeJs Katalog API)")
Component(getServiceCategoryList, "getServiceCategoryList", "Function | NodeJs", "Function for Get service category list\n(NodeJs Katalog API)")
Component(getServiceItemList, "getServiceItemList", "Function | NodeJs", "Function for Get service item list\n(NodeJs Katalog API)")
Component(gets, "getServiceReminderConfig", "Function | NodeJs", "Function for Get Service reminder config\n(NodeJs Katalog API)")
Component(getServiceUmumByBengkelID, "getServiceUmumByBengkelID", "Function | NodeJs", "Function for Get Service Umum By ID, Bengkel ID, Service Umum List\n(NodeJs Katalog API)")
Component(listMultiConditionCategoryItem, "listMultiConditionCategoryItem", "Function | NodeJs", "Function for List Multi Condition Category Item\n(NodeJs Katalog API)")
Component(listMultiConditionServiceBerkalaItem, "listMultiConditionServiceBerkalaItem", "Function | NodeJs", "Function for List Multi Condition Service Berkala Item\n(NodeJs Katalog API)")
Component(readByBengkelID, "readByBengkelID", "Function | NodeJs", "Function for Read service berkala, service umum data by bengkel ID\n(NodeJs Katalog API)")
Component(readByServiceBerkalaID, "readByServiceBerkalaID", "Function | NodeJs", "Function for Read data by service berkala ID\n(NodeJs Katalog API)")
Component(updateServiceBerkala, "ServiceBerkala.updateServiceBerkala", "Function | NodeJs", "Function for Update data service berkala, service umum\n(NodeJs Katalog API)")
Component(update, "Update Service Reminder", "Function | NodeJs", "Function for Show & Update Service Reminder Config\n(NodeJs Katalog API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, API, "Request use function related to Katalog")

Rel(API, bookingGetBrandList, "Request Get booking brand list")
Rel(API, bookingGetCarModelList, "Request Get booking car model list")
Rel(API, createByBengkelID, "Request Create service berkala data by bengkel ID")
Rel(API, createItemByCategoryID, "Request Create Item By Category ID")
Rel(API, create, "Request Create Service Berkala & Reminder data")
Rel(API, delete, "Request Delete Service Reminder Config, Delete Service Berkala by ID, Delete Service Umum by ID")
Rel(API, getAllParam, "Request Get all mobil param")
Rel(API, getAllServiceItemAndCategory, "Request Get all service item and category")
Rel(API, getBrandList, "Request Get brand list")
Rel(API, getModelList, "Request Get model list")
Rel(API, getRefTipeServis, "Request Get tipe servis data")
Rel(API, getServiceBerkalaForBookingByBengkelIDApp, "Request Get Service Berkala For Booking By Bengkel ID")

Rel(API, getServiceBerkalaKMList, "Request Get service berkala KM list")
Rel(API, getServiceCategoryList, "Request Get service category list")
Rel(API, getServiceItemList, "Request Get service item list")
Rel(API, gets, "Request Get Service reminder config")
Rel(API, getServiceUmumByBengkelID, "Request Get Service Umum By ID, Bengkel ID, Service Umum List")
Rel(API, listMultiConditionCategoryItem, "Request List Multi Condition Category Item")
Rel(API, listMultiConditionServiceBerkalaItem, "Request List Multi Condition Service Berkala Item")
Rel(API, readByBengkelID, "Request Read service berkala, service umum data by bengkel ID")
Rel(API, readByServiceBerkalaID, "Request Read data by service berkala ID")
Rel(API, updateServiceBerkala, "Request Update data service berkala, service umum")
Rel(API, update, "Request Show & Update Service Reminder Config")

Rel(bookingGetBrandList, database, "Request Get booking brand list")
Rel(bookingGetCarModelList, database, "Request Get booking car model list")
Rel(createByBengkelID, database, "Request Create service berkala data by bengkel ID")
Rel(createItemByCategoryID, database, "Request Create Item By Category ID")
Rel(create, database, "Request Create Service Berkala & Reminder data")
Rel(delete, database, "Request Delete Service Reminder Config, Delete Service Berkala by ID, Delete Service Umum by ID")
Rel(getAllParam, database, "Request Get all mobil param")
Rel(getAllServiceItemAndCategory, database, "Request Get all service item and category")
Rel(getBrandList, database, "Request Get brand list")
Rel(getModelList, database, "Request Get model list")
Rel(getRefTipeServis, database, "Request Get tipe servis data")
Rel(getServiceBerkalaForBookingByBengkelIDApp, database, "Request Get Service Berkala For Booking By Bengkel ID")

Rel(getServiceBerkalaKMList, database, "Request Get service berkala KM list")
Rel(getServiceCategoryList, database, "Request Get service category list")
Rel(getServiceItemList, database, "Request Get service item list")
Rel(gets, database, "Request Get Service reminder config")
Rel(getServiceUmumByBengkelID, database, "Request Get Service Umum By ID, Bengkel ID, Service Umum List")
Rel(listMultiConditionCategoryItem, database, "Request List Multi Condition Category Item")
Rel(listMultiConditionServiceBerkalaItem, database, "Request List Multi Condition Service Berkala Item")
Rel(readByBengkelID, database, "Request Read service berkala, service umum data by bengkel ID")
Rel(readByServiceBerkalaID, database, "Request Read data by service berkala ID")
Rel(updateServiceBerkala, database, "Request Update data service berkala, service umum")
Rel(update, database, "Request Show & Update Service Reminder Config")