@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getServiceBerkalaKMList API\n[NodeJs Katalog API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "getServiceBerkalaKMList API\n[Component]"){
Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Middleware for Verification\n(NodeJs Katalog API)")
Component(reference_controller, "Service Berkala Item Controller", "Controller | NodeJs", "Controller for Service Berkala Item Related function\n(NodeJs Katalog API)")
Component(getServiceCategoryList, "getServiceBerkalaKMList", "Function | NodeJs", "Function for get service berkala list\n(NodeJs Katalog API)")
Component(getCategory, "Ref_service_berkala_km.getServiceBerkalaKM", "Function | NodeJs", "Function for get service berkala data\n(NodeJs Katalog API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request get service berkala list")
Rel_D(auth_middleware, reference_controller, "2. Request get service berkala list")
Rel_D(reference_controller, getServiceCategoryList, "3. Request get service berkala list")
Rel_D(getServiceCategoryList, getCategory, "4. Request get service berkala list")
Rel_D(getCategory, database, "5. Get service berkala list")

@enduml