@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getBrandList Moadmin API\n[NodeJs Katalog API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "getBrandList Moadmin API\n[Component]"){

Component(auths_middlewares, "auth.verify", "Middleware | NodeJs", "Middleware for verify\n(NodeJs Katalog API)")
Component(reference_controller, "Reference Controller", "Controller | NodeJs", "Controller for Reference Related function\n(NodeJs Katalog API)")
Component(getBrandList, "getBrandList", "Function | NodeJs", "Function for get brand list\n(NodeJs Katalog API)")
Component(getBrand, "Mobil.getBrand", "Function | NodeJs", "Function for get brand mobil\n(NodeJs Katalog API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auths_middlewares, "1. Request get brand mobil")

Rel_D(auths_middlewares, reference_controller, "2. Request get brand mobil")

Rel_D(reference_controller, getBrandList, "3. Request get brand mobil")
Rel_D(getBrandList, getBrand, "4. Request get brand mobil")

Rel_D(getBrand, database, "5. Get brand mobil")

@enduml