@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title listMultiConditionCategoryItem Service Umum API\n[NodeJs Katalog API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "listMultiConditionCategoryItem Service Umum API\n[Component]"){

Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Middleware for Verification\n(NodeJs Katalog API)")
Component(reference_controller, "Service Umum Category Item Controller", "Controller | NodeJs", "Controller for Service Umum Category Item Related function\n(NodeJs Katalog API)")

Component(listMultiConditionCategoryItem, "listMultiConditionCategoryItem", "Function | NodeJs", "Function for list Multi Condition Category Item\n(NodeJs Katalog API)")
Component(countAllFilter, "Ref_service_umum_item.countAllFilter", "Function | NodeJs", "Function for count all filter data\n(NodeJs Katalog API)")
Component(getAllMultiCondition, "Ref_service_umum_item.getAllMultiCondition", "Function | NodeJs", "Function for get all multi condition\n(NodeJs Katalog API)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, auth_middleware, "1. Request list Multi Condition Category Item")
Rel_D(auth_middleware, reference_controller, "2. Request list Multi Condition Category Item")

Rel_D(reference_controller, listMultiConditionCategoryItem, "3. Request list Multi Condition Category Item")
Rel_D(listMultiConditionCategoryItem, countAllFilter, "4. Request Count all filter data")
Rel_D(listMultiConditionCategoryItem, getAllMultiCondition, "6. Request get all multi condition")
Rel_D(countAllFilter, database, "5. Count All filter data")
Rel_D(getAllMultiCondition, database, "7. Get All Multi Condition")

@enduml