@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title updateByServiceUmumID Service Umum API\n[NodeJs Katalog API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "updateByServiceUmumID Service Umum API\n[Component]"){
Component(auth_middleware, "user.login", "Function | NodeJs", "Function for login\n(NodeJs Katalog API)")

Component(auth_middlewares, "auth.verify", "Middleware | NodeJs", "Middleware for Verification\n(NodeJs Katalog API)")
Component(reference_controller, "Service Umum Controller", "Controller | NodeJs", "Controller for Service Umum Related function\n(NodeJs Katalog API)")
Component(updateByServiceUmumID, "updateByServiceUmumID", "Function | NodeJs", "Function for Update service umum data by Service Umum ID\n(NodeJs Katalog API)")
Component(Update, "ServiceUmum.updateServiceUmum", "Function | NodeJs", "Function for Update service umum data\n(NodeJs Katalog API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request Update service umum data by Service Umum ID")
Rel_D(auth_middleware, auth_middlewares, "2. Request Update service umum data by Service Umum ID")
Rel_D(auth_middlewares, reference_controller, "3. Request Update service umum data by Service Umum ID")
Rel_D(reference_controller, updateByServiceUmumID, "4. Update service umum data by Service Umum ID")
Rel_D(updateByServiceUmumID, Update, "5. Request Update service umum data")
Rel_D(Update, database, "6. Update service umum data")

@enduml