@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Get Single Listing Item API\n[listingItem]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")

    Boundary(middleware, "middleware catalog API\n[Component]"){

        Component(validate_query, "validateRequestQuery", "Middleware | NodeJS", "Middleware for validate request query\n{ms-catalog}")
        Component(catalog_middleware, "verifyListingGetById", "Middleware | NodeJS", "Middleware for check catalog param\n{ms-catalog}")

    }
    
    Boundary(api, "getListingItemById API\n[Component]"){

        Component(getListingItem, "getListingItem", "Function | NodeJS", "API for find & search Catalog by id\n{ms-catalog}")

    }
    ContainerDb(momo_x_elasticsearch, "Momo X Elastic Search", "Elastic Search", "Storage elastic search for catalog momo x")


Rel_D(web_momo_x, validate_query, "1. Validate request query")
Rel_D(validate_query, catalog_middleware, "2. Check request id")
Rel_R(catalog_middleware, getListingItem, "3. Request search listing item by id")
Rel_D(getListingItem, momo_x_elasticsearch, "4. Get data listing item by id")


SHOW_LEGEND()
@enduml