@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Get Listing Item API\n[listingItem]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")
    
    Boundary(api, "getListingItem API\n[Component]"){

        Component(catalog_middleware, "verifyListingGetAll", "Middleware | NodeJS", "Middleware for check catalog param\n{ms-catalog}")
        Component(getListingItem, "getListingItem", "Function | NodeJS", "API for find & search Catalog by filter\n{ms-catalog}")

    }
    ContainerDb(momo_x_elasticsearch, "Momo X Elastic Search", "Elastic Search", "Storage elastic search for catalog momo x")


Rel_D(web_momo_x, catalog_middleware, "1. Check request category")
Rel_R(catalog_middleware, getListingItem, "2. Request search listing item by filter")
Rel_D(getListingItem, momo_x_elasticsearch, "3. Get data listing item by filter")


SHOW_LEGEND()
@enduml