@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Get Listing Item API\n[listingItem]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")

    Boundary(middleware, "middleware catalog API\n[Component]"){

        Component(validate_query, "validateRequestQuery", "Middleware | NodeJS", "Middleware for validate request query\n{ms-catalog}")
        Component(verify_token, "verifyToken", "Middleware | NodeJS", "Middleware check bearer token\n{ms-catalog}")
        Component(catalog_middleware, "verifyListingGetAll", "Middleware | NodeJS", "Middleware for check catalog param\n{ms-catalog}")

    }
    
    Boundary(api, "getListingItem API\n[Component]"){
        
        Component(getListingItem, "getListingItem", "Function | NodeJS", "API for find & search Catalog by filter\n{ms-catalog}")

    }
    ContainerDb(momo_x_elasticsearch, "Momo X Elastic Search", "Elastic Search", "Storage elastic search for catalog momo x")


Rel_D(web_momo_x, verify_token, "1A. (if get listing seller) Check token request")
Rel_D(web_momo_x, validate_query, "1B. Validate request query")
Rel_D(verify_token, validate_query, "2A. Validate request query")
Rel_D(validate_query, catalog_middleware, "3. Check request")
Rel_R(catalog_middleware, getListingItem, "4. Request search listing item by filter")
Rel_D(getListingItem, momo_x_elasticsearch, "5. Get data listing item by filter")


SHOW_LEGEND()
@enduml