@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Get User Action API\n[getUserAction]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")

    Boundary(middleware, "middleware catalog API\n[Component]"){

        Component(decrypt_body, "validateRequestBody", "Middleware | NodeJS", "Middleware for decrypt request body\n{ms-catalog}")

    }
    
    Boundary(api, "getUserAction API\n[Component]"){

        Component(getUserAction, "getUserAction", "Function | NodeJS", "API for get data user action\n{ms-catalog}")

    }
    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for catalog momo x")


Rel_D(web_momo_x, decrypt_body, "1. Decrypt & validate request body")
Rel_D(decrypt_body, getUserAction, "2. Request get all data user action")
Rel_D(getUserAction, momo_x_storage, "3. Get all data user action")

SHOW_LEGEND()
@enduml