@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Update Listing Item Status API\n[updateListingStatus]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Customer")

    Boundary(middleware, "middleware catalog API\n[Component]"){

        Component(verify_token, "verifyToken", "Middleware | NodeJS", "Middleware check bearer token\n{ms-catalog}")
        Component(validate_query, "validateRequestQuery", "Middleware | NodeJS", "Middleware for validate query\n{ms-catalog}")
        Component(catalog_middleware, "verifyListingUpdateStatus", "Middleware | NodeJS", "Middleware for check update catalog param\n{ms-catalog")

    }
    
    Boundary(api, "updateListingStatus API\n[Component]"){

        Component(updateListingStatus, "updateListingStatus", "Function | NodeJS", "API update data catalog \n{ms-catalog}")

    }
    ContainerDb(momo_x_elasticsearch, "Momo X Elastic Search", "Elastic Search", "Storage elastic search for catalog momo x")
    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for catalog momo x")


Rel_D(web_momo_x, verify_token, "1. Verify token")
Rel_R(verify_token, validate_query, "2. Validate request query")
Rel_D(validate_query, catalog_middleware, "3. Check request body")
Rel_R(catalog_middleware, updateListingStatus, "4. Request update listing status")
Rel_D(updateListingStatus, momo_x_storage, "5. Update data listing status")
Rel_R(updateListingStatus, momo_x_elasticsearch, "6. Update data listing status")

SHOW_LEGEND()
@enduml