@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title changePassword API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "changePassword API\n[Component]"){
Component(user_controller, "Users Controller", "Controller | NodeJs", "Controller for User Related function\n(NodeJs User API)")
Component(changePassword, "changePassword", "Function | NodeJs", "Function for change password\n(NodeJs User API)")
Component(PasswordValidator, "PasswordValidator", "Function | NodeJs", "Function for validate password\n(NodeJs User API)")
Component(user, "user", "Function | NodeJs", "Function for retrieve user data\n(NodeJs User API)")
Component(validateHash, "encryption.validateHash", "Function | NodeJs", "Function for check password\n(NodeJs User API)")
Component(createPassword, "encryption.createPassword", "Function | NodeJs", "Function for create password\n(NodeJs User API)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, user_controller, "1. Request reset Password")
Rel_D(user_controller, changePassword, "2. Request reset Password")
Rel_D(changePassword, PasswordValidator, "3. Validate Password")
Rel_D(changePassword, user, "4. Request retrieve user data")
Rel_D(user, database, "5. Retrieve user data")

Rel_D(changePassword, validateHash, "6. Request check password")
Rel_D(validateHash, database, "7. Check Password")

Rel_D(changePassword, createPassword, "8. Request Create Password")
Rel_D(createPassword, database, "9. Create Password")

@enduml