@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title checkCurrentPassword API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "checkCurrentPassword API\n[Component]"){
Component(auth_middleware, "auth.validateBengkelId", "Middleware | NodeJs", "Middleware for validate bengkel ID\n(NodeJs User API)")
Component(auths_middleware, "auth.verify", "Middleware | NodeJs", "Middleware for authentication\n(NodeJs User API)")
Component(user_controller, "User Workshop Controller", "Controller | NodeJs", "Controller for User Workshop Related function\n(NodeJs User API)")
Component(checkCurrentPassword, "checkCurrentPassword", "Function | NodeJs", "Function for check Current Password\n(NodeJs User API)")
Component(getUserBengkelbyBengkelID, "UsersWorkshop.getUserBengkelbyBengkelID", "Function | NodeJs", "Function for get User Bengkel by Bengkel ID\n(NodeJs User API)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request Check Current Password")

Rel_D(auth_middleware, auths_middleware, "2. Request Check Current Password")
Rel_D(auths_middleware, user_controller, "3. Request Check Current Password")
Rel_D(user_controller, checkCurrentPassword, "4. Check Current Password")
Rel_D(checkCurrentPassword, getUserBengkelbyBengkelID, "5. Request Get User Bengkel by Bengkel ID")
Rel_D(getUserBengkelbyBengkelID, database, "6. Get User Bengkel by Bengkel ID")

@enduml