@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title forgotPassword Moservice API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "forgotPassword Moservice API\n[Component]"){
Component(Limiter, "Limiter", "Function | NodeJs", "Function for Limiter")
Component(user_controller, "Moservice Users Controller", "Controller | NodeJs", "Controller for Moservice User Related function\n(NodeJs User API)")
Component(forgotPassword, "forgotPassword", "Function | NodeJs", "Function for forgot password\n(NodeJs User API)")
Component(forgotPasswords, "usersMoserviceCRUD.forgotPassword", "Function | NodeJs", "Function for forgot password\n(NodeJs User API)")
Component(getUserIDByEmail, "UsersMoservice.getUserIDByEmail", "Function | NodeJs", "Function for get user ID by Email\n(NodeJs User API)")
Component(generate, "otp.generate", "Function | NodeJs", "Function for generate OTP\n(NodeJs User API)")

Component(createTableIfNotExist, "OTP.createTableIfNotExist", "Function | NodeJs", "Function for create table non exist\n(NodeJs User API)")
Component(create, "OTP.create", "Function | NodeJs", "Function for create OTP\n(NodeJs User API)")
Component(sendSMS, "message.sendSMS", "Function | NodeJs", "Function for send SMS\n(NodeJs User API)")
Component(sendEmail, "message.sendEmail", "Function | NodeJs", "Function for send Email\n(NodeJs User API)")
Component(sendMail, "transporter.sendMail", "Function | NodeJs", "Function for send Email\n(NodeJs User API)")
}

AddProperty("URL", "/sms/2/text/single")
System_Ext(infoBIP, "InfoBIP", "External System for Send SMS")

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Lay_D(sendMail, infoBIP)
Rel_D(Web_Moservice, Limiter, "1. Request Forgot Password")

Rel_D(Limiter, user_controller, "2. Request Forgot Password")
Rel_D(user_controller, forgotPassword, "3. Request Forgot Password")
Rel_D(forgotPassword, forgotPasswords, "4. Request Forgot Password")
Rel_R(forgotPasswords, getUserIDByEmail, "5. Request get user id by email")
Rel_D(forgotPasswords, generate, "7. Request generate OTP data")
Rel_D(generate, createTableIfNotExist, "9. Request Create table data")
Rel_D(generate, create, "11. Request Create OTP")
Rel_D(generate, sendSMS, "13. If SMS, Request Send SMS")
Rel_D(generate, sendEmail, "13. If Email, Request Send Email")
Rel_D(sendEmail, sendMail, "14. Send Email")
Rel_D(sendSMS, infoBIP, "14. Send SMS")



Rel_D(getUserIDByEmail, database, "6. Get user id by email")
Rel_D(generate, database, "8. Generate OTP data")
Rel_D(createTableIfNotExist, database, "10. Create table data")
Rel_D(create, database, "12. Create OTP")

@enduml