@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title resetPassword API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "resetPassword API\n[Component]"){
Component(user_controller, "Users Controller", "Controller | NodeJs", "Controller for User Related function\n(NodeJs User API)")
Component(resetPassword, "resetPassword", "Function | NodeJs", "Function for reset password\n(NodeJs User API)")
Component(PasswordValidator, "PasswordValidator", "Function | NodeJs", "Function for validate password\n(NodeJs User API)")
Component(createPassword, "encryption.createPassword", "Function | NodeJs", "Function for create password\n(NodeJs User API)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, user_controller, "1. Request reset Password")
Rel_D(user_controller, resetPassword, "2. Request reset Password")
Rel_D(resetPassword, PasswordValidator, "4. Request Validate Password")
Rel_D(resetPassword, createPassword, "6. Request Create Password")
Rel_D(resetPassword, database, "3. Retrieve User Password data")
Rel_D(PasswordValidator, database, "5. Validate Password")
Rel_D(createPassword, database, "7. Create Password")


@enduml