@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title createPilihanLainImage API\n[NodeJs Content API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")

Boundary(api, "createPilihanLainImage API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for verification Function\n(NodeJs Content API)")
    Component(content_controller, "Content Pilihan Lain Controller", "Controller | NodeJs", "Controller for Content Pilihan Lain Related Function\n(NodeJs Content API)")
    Component(createPilihanLainImage, "createPilihanLainImage", "Function | NodeJs", "Function for Create Pilihan Lain Image data\n(NodeJs Content API)")
    Component(readDetail, "ContentPilihanLain.readDetail", "Function | NodeJs", "Function for Read detail Pilihan Lain data\n(NodeJs Content API)")
    Component(upload, "cloudinary.uploader.upload", "Function | NodeJs", "Function for Upload Cloudinary\n(NodeJs Content API)")
    Component(update, "ContentPilihanLain.update", "Function | NodeJs", "Function for Update Pilihan Lain Image data\n(NodeJs Content API)")

}

AddProperty("URL", "https://res.cloudinary.com/adiramoservice/q_auto,f_auto/${version}/${cloudinaryPath}")
System_Ext(Clodinary, "Cloudinary", "External System for Store Image data")

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Create Pilihan Lain data")
Rel(auth_middleware, content_controller, "2. Request Create Pilihan Lain data")
Rel(content_controller, createPilihanLainImage, "3. Request Create Pilihan Lain data")
Rel(createPilihanLainImage, readDetail, "4. Request Read detail Pilihan Lain data")
Rel(createPilihanLainImage, upload, "6. Request Upload Pilihan Lain data")
Rel(createPilihanLainImage, update, "8. Request Update Pilihan Lain Image data")

Rel_L(upload, Clodinary, "7. Upload Pilihan Lain data")

Rel(readDetail, database, "5. Read detail Pilihan Lain data")
Rel(update, database, "9. Update Pilihan Lain Image data")

@enduml