@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title delete Banner API\n[NodeJs Content API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")

Boundary(api, "delete Banner API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for verification Function\n(NodeJs Content API)")
    Component(content_controller, "Content Banner Controller", "Controller | NodeJs", "Controller for Banner Related Function\n(NodeJs Content API)")
    Component(delete, "delete", "Function | NodeJs", "Function for Delete Moadmin banner data\n(NodeJs Content API)")
    Component(deletes, "ContentBanner.delete", "Function | NodeJs", "Function for delete Moadmin banner data\n(NodeJs Content API)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Delete Moadmin banner data")
Rel(auth_middleware, content_controller, "2. Request Delete Moadmin banner data")
Rel(content_controller, delete, "3. Request Delete Moadmin banner data")
Rel(delete, deletes, "4. Request Delete Moadmin banner data")

Rel(deletes, database, "5. Delete Moadmin banner data")

@enduml