@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getListTransaction Content Promo API\n[NodeJs Content API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")

Boundary(api, "getListTransaction Content Promo API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for verification Function\n(NodeJs Content API)")
    Component(multer_middleware, "multer.diskStorage", "Middleware | NodeJs", "Set Multer Storage\n(NodeJs Content API)")
    Component(content_controller, "Content Promo Controller", "Controller | NodeJs", "Controller for Content Promo Related Function\n(NodeJs Content API)")
    
    Component(getListTransaction, "getListTransaction", "Function | NodeJs", "Function for Get List Transaction\n(NodeJs Content API)")
    Component(getListTransactions, "ContentPromo.getListTransaction", "Function | NodeJs", "Function for Get List Transaction\n(NodeJs Content API)")
    Component(countListTransaction, "ContentPromo.countListTransaction", "Function | NodeJs", "Function for Count list transaction\n(NodeJs Content API)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, multer_middleware, "1. Set Up Storage")
Rel(multer_middleware, auth_middleware, "2. Request Get List Transaction")

Rel(auth_middleware, content_controller, "3. Request Get List Transaction")
Rel(content_controller, getListTransaction, "4. Request Get List Transaction")
Rel(getListTransaction, getListTransactions, "5. Request Get List Transaction")
Rel(getListTransaction, countListTransaction, "7. Request Count list transaction")

Rel(getListTransactions, database, "6. Get List Transaction")
Rel(countListTransaction, database, "8. Count list transaction")

@enduml