@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title readList Content Promo API\n[NodeJs Content API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")

Boundary(api, "readList Content Promo API\n[Component]"){
    Component(multer_middleware, "multer.diskStorage", "Middleware | NodeJs", "Set Multer Storage\n(NodeJs Content API)")
    Component(auth_middleware, "auth.validate", "Middleware | NodeJs", "Authentication Middleware for validate Function\n(NodeJs Content API)")
    Component(content_controller, "Content Promo Controller", "Controller | NodeJs", "Controller for Content Promo Related Function\n(NodeJs Content API)")
    Component(readList, "readList", "Function | NodeJs", "Function for read list promo data\n(NodeJs Content API)")
    Component(readLists, "ContentPromo.readList", "Function | NodeJs", "Function for read list promo data\n(NodeJs Content API)")
    Component(countList, "ContentPromo.countList", "Function | NodeJs", "Function for count list promo data\n(NodeJs Content API)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, multer_middleware, "1. Set Up Storage")
Rel(multer_middleware, auth_middleware, "2. Request Read list Promo data")
Rel(auth_middleware, content_controller, "3. Request Read list Promo data")
Rel(content_controller, readList, "4. Request Read list Promo data")
Rel(readList, readLists, "5. Request Read list Promo data")
Rel(readList, countList, "7. Request Count list Promo data")

Rel(readLists, database, "6. Read list Promo data")
Rel(countList, database, "8. Count list Promo data")

@enduml