@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title readDetail Pilihan lain API\n[NodeJs Content API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")

Boundary(api, "readDetail Pilihan lain API\n[Component]"){
    Component(auth_middleware, "auth.verify", "Middleware | NodeJs", "Authentication Middleware for verification Function\n(NodeJs Content API)")
    Component(content_controller, "Content Pilihan Lain Controller", "Controller | NodeJs", "Controller for Content Pilihan Lain Related Function\n(NodeJs Content API)")
    Component(readDetail, "readDetail", "Function | NodeJs", "Function for Read Detail Pilihan Lain data\n(NodeJs Content API)")
    Component(readDetails, "ContentPilihanLain.readDetail", "Function | NodeJs", "Function for Read Detail Pilihan Lain data\n(NodeJs Content API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, auth_middleware, "1. Request Read Detail Pilihan Lain data")
Rel(auth_middleware, content_controller, "2. Request Read Detail Pilihan Lain data")
Rel(content_controller, readDetail, "3. Request Read Detail Pilihan Lain data")
Rel(readDetail, readDetails, "4. Request Read Detail Pilihan Lain data")

Rel(readDetails, database, "5. Read Detail Pilihan Lain data")

@enduml