@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title redeemMultiple Content Promo API\n[NodeJs Content API]

Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")

Boundary(api, "redeemMultiple Content Promo API\n[Component]"){
    Component(multer_middleware, "multer.diskStorage", "Middleware | NodeJs", "Set Multer Storage\n(NodeJs Content API)")
    Component(auth_middleware, "auth.validate", "Middleware | NodeJs", "Authentication Middleware for validate Function\n(NodeJs Content API)")
    Component(content_controller, "Content Promo Controller", "Controller | NodeJs", "Controller for Content Promo Related Function\n(NodeJs Content API)")
    Component(checkDateController, "checkDateController", "Function | NodeJs", "Function for check date for promo\n(NodeJs Content API)")
    Component(checkDate, "ContentPromo.checkDate", "Function | NodeJs", "Function for check date for promo data\n(NodeJs Content API)")
    Component(redeemMultiplePromoController, "redeemMultiplePromoController", "Function | NodeJs", "Function for redeem multiple promo controller\n(NodeJs Content API)")
    Component(redeemMultiple, "ContentPromo.redeemMultiple", "Function | NodeJs", "Function for redeem multiple promo\n(NodeJs Content API)")
    Component(QRCode, "QRCode.toDataURL", "Function | NodeJs", "Function for create QR Code\n(NodeJs Content API)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, multer_middleware, "1. Set Up Storage")
Rel(multer_middleware, auth_middleware, "2. Request Redeem multiple promo")
Rel(auth_middleware, content_controller, "3. Request Redeem multiple promo")

Rel(content_controller, checkDateController, "4. Request Redeem multiple promo")
Rel(checkDateController, checkDate, "5. Request Check date for promo")

Rel(content_controller, redeemMultiplePromoController, "7. Request Redeem multiple promo")
Rel(redeemMultiplePromoController, redeemMultiple, "8. Request Redeem multiple promo")
Rel(redeemMultiplePromoController, QRCode, "10. Request Create QR Code")

Rel(checkDate, database, "6. Check date for Promo, if there is promo Continue to 7. If there is no promo Stop.")
Rel(redeemMultiple, database, "9. Redeem Multiple Promo")


@enduml