@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Prospect

AddProperty("repository", "MS-Authentication")
AddProperty("url", "/api/v1/auth/pin-v4")
Component(createValidatePIN, "Create or Validate PIN API", "microservices | NodeJS", "Create or Validate PIN")

System_Boundary(pinv4, "Controller API pin-v4") {
    Component(encrypt, "Enkripsi Key", "Function")
    Component(jwt, "Sign JWT", "Function")
}

AddProperty("repository", "MS-Loyalty")
AddProperty("url", "/api/v1/validate-pin-prospect")
Component(validatePINProspect, "Validate PIN Prospect API", "microservices | NodeJS", "Validate pin prospect")

AddProperty("repository", "MS-Loyalty")
AddProperty("url", "/api/v1/update-active-device-id-prospect")
Component(updateActiveDeviceIdProspect, "Update Active Device ID Prospect API", "microservices | NodeJS", "Update active device id prospect")

AddProperty("repository", "MS-Loyalty")
AddProperty("url", "/api/v1/create-pin-prospect")
Component(createPINProspect, "Create PIN Prospect API", "microservices | NodeJS", "Create pin prospect")

'PIN
Rel(createValidatePIN, validatePINProspect, "1. IF have PIN, validate PIN")
Rel(validatePINProspect, encrypt, "2. Encrypt Data")
Rel(encrypt, jwt, "3. Create new JWT")
Rel(jwt, updateActiveDeviceIdProspect, "4. Send Token, update Device Id")

'Don't Have PIN
Rel(createValidatePIN, createPINProspect, "1. If don't have PIN, create PIN")
Rel(createPINProspect, encrypt, "2. Encrypt Data")

@enduml
