@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title Component Diagram for Request Notification Bulk Insider\n (api/v1/notification-insider/request-notification-bulk)

AddProperty("URL", "ms-batch\api\v1\birthday\controller.js")
AddProperty("Repository", "ms-batch")
Component(birthday, "birthday", "Function | NodeJs", "Function for Birthday Notification")

AddProperty("URL", "/api/v1/user-get-user/reminder-contract")
AddProperty("Repository", "ms-marketing")
Component(reminderContract, "reminderContract", "Function | NodeJs", "Function for Reminder Contract Process")

Boundary(api, "requestPushNotificationBulk API\n[Component]"){
    AddProperty("Path", "ms-notification\api\v1\Notification\controller.js")
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller for Notification Related Function")

    Component(requestPushNotificationBulk, "requestPushNotificationBulk", "Function | NodeJs", "Function for Request Push Notification bulk") 

}
AddProperty("URL", "process.env.INSIDER_NOTIF_URL")
System_Ext(insider, "Insider", "External System for Notification") 

AddProperty("URL", "process.env.MS_ACTIVITY + '/activity/bulk'")
AddProperty("Repository", "ms-activity")
Component(postActivityBulk, "postActivityBulk", "Function | NodeJs", "Function for Create Bulk Activity")

ComponentDb(database, "Adiraku Storage", "mySql Storage", "CampaignInsider")

Rel(birthday, controller, "1. API CALL")
Rel(reminderContract, controller, "1. API CALL")
Rel(controller, requestPushNotificationBulk, "2. Request Notification Bulk Insider")
Rel(requestPushNotificationBulk, database, "3. Find campaign data (CampaignInsider)")
Rel(requestPushNotificationBulk, database, "3. Else if (!campaign), Create campaign data (CampaignInsider)")
Rel(requestPushNotificationBulk, database, "4. Retrieve campaign data (CampaignInsider)")
Rel_L(requestPushNotificationBulk, insider, "5. Retrieve Insider Response")
Rel_R(requestPushNotificationBulk, postActivityBulk, "6. Create Bulk Activity")