@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title create digital specialist API\n[mos-bengkel-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "create digital specialist API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-bengkel-service)")
Component(digital_specialist_controller, "Digital Specialist Controller", "Controller | TypeScript", "Controller for Digital Specialist Related Function\n(mos-bengkel-service)")
Component(auth_operator_middleware, "Auth Operator Middleware", "Middleware | TypeScript", "Middleware for Authentication\n(mos-bengkel-service)")
Component(create, "create", "Function | TypeScript", "Main Function for create digital specialist data\n(mos-bengkel-service)")
Component(DigitalSpecialistRepositorycreate, "DigitalSpecialistRepository.create", "Function | TypeScript", "Main Function for create digital specialist data\n(mos-bengkel-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, mainMiddleware, "1. Request create digital specialist data")

Rel_D(mainMiddleware, auth_operator_middleware, "2. Request create digital specialist data")
Rel_D(auth_operator_middleware, digital_specialist_controller, "3. Request create digital specialist data")
Rel_D(digital_specialist_controller, create, "4. Request create digital specialist data")
Rel_D(create, DigitalSpecialistRepositorycreate, "5. Create Digital Specialist Data")
Rel_D(DigitalSpecialistRepositorycreate, database, "6. Create Digital Specialist Data")

@enduml