@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title landingPage API\n[mos-bengkel-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "landingPage API\n[Component]"){
Component(bengkel_controller, "Bengkel Controller", "Controller | TypeScript", "Controller for Bengkel Related Function\n(mos-bengkel-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-bengkel-service)")
Component(landingPage, "landingPage", "Function | TypeScript", "Main Function for bengkel list at landing page\n(mos-bengkel-service)")

}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, mainMiddleware, "1. Request show all bengkel list")

Rel_D(mainMiddleware, bengkel_controller, "2. Request show all bengkel list")
Rel_D(bengkel_controller, landingPage, "3. Request show all bengkel list")
Rel_D(landingPage, database, "4. Retrieve all bengkel List Data")

@enduml