@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title registration bengkel API\n[mos-bengkel-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "registration bengkel API\n[Component]"){
Component(bengkel_controller, "Bengkel Controller", "Controller | TypeScript", "Controller for Bengkel Related Function\n(mos-bengkel-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-bengkel-service)")
Component(registration_bengkel, "registrationBengkel", "Function | TypeScript", "Main Function for Register Bengkel Data\n(mos-bengkel-service)")
Component(registration_bengkel_save, "BengkelRegistrationRepository.save", "Function | TypeScript", "Main Function for Register Bengkel Data\n(mos-bengkel-service)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, mainMiddleware, "1. Request Register Bengkel Data")

Rel_D(mainMiddleware, bengkel_controller, "2. Request Register Bengkel Data")
Rel_D(bengkel_controller, registration_bengkel, "3. Request Register Bengkel Data")
Rel_D(registration_bengkel, registration_bengkel_save, "4. Register Bengkel Data")
Rel_D(registration_bengkel_save, database, "5. Save Bengkel Data")

@enduml