@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
LAYOUT_WITH_LEGEND()
title updateEspayCredentials API\n[mos-bengkel-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "updateEspayCredentials API\n[Component]"){
Component(group_bengkel_controller, "Group Bengkel Controller", "Controller | TypeScript", "Controller for Group Bengkel Related Function\n(mos-bengkel-service)")
Component(auth_operator_middleware, "Auth Operator Middleware", "Middleware | TypeScript", "Middleware for Authentication\n(mos-bengkel-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-bengkel-service)")
Component(updateEspayCredentials, "updateEspayCredentials", "Function | TypeScript", "Main Function for update Espay Credential data\n(mos-bengkel-service)")
Component(updateEspayCredentialsByGroupBengkel, "updateEspayCredentialsByGroupBengkel", "Function | TypeScript", "Function for update Espay Credential data by Group Bengkel\n(mos-bengkel-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
AddProperty("Topic", "update-espay-credential-by-groupbengkel")
SystemQueue(Kafka, "Kafka")
Rel_D(Web_Moservice, mainMiddleware, "1. Request update Espay Credential data")

Rel_D(mainMiddleware, auth_operator_middleware, "2. Request update Espay Credential data")
Rel_D(auth_operator_middleware, group_bengkel_controller, "3. Request update Espay Credential data")
Rel_D(group_bengkel_controller, updateEspayCredentials, "4. Request update Espay Credential data")
Rel_R(updateEspayCredentials, database, "5. Retrieve Group Bengkel Data")
Rel_D(updateEspayCredentials, updateEspayCredentialsByGroupBengkel, "6. Request update Espay Credential data")
Rel_D(updateEspayCredentialsByGroupBengkel, Kafka, "7. Update Espay Credential data")
@enduml