@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title ChangePasswordfromApp API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "ChangePasswordfromApp API\n[Component]"){
Component(validateBengkelId, "auth.validateBengkelId", "Middleware | NodeJs", "Middleware for validate bengkel ID\n(NodeJs User API)")
Component(pass_controller, "Bengkel Pass Controller", "Controller | NodeJs", "Controller for Bengkel Pass Related function\n(NodeJs User API)")
Component(ChangePasswordfromApp, "ChangePasswordfromApp", "Function | NodeJs", "Function for Change Password from App\n(NodeJs User API)")

Component(getUserBengkelbyBengkelID, "UsersWorkshop.getUserBengkelbyBengkelID", "Function | NodeJs", "Function for get User Bengkel by Bengkel ID\n(NodeJs User API)")
Component(updatePassword, "UsersWorkshop.updatePassword", "Function | NodeJs", "Function for update Password\n(NodeJs User API)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, validateBengkelId, "1. Request Change Password from App")

Rel_D(validateBengkelId, pass_controller, "2. Request Change Password from App")
Rel_D(pass_controller, ChangePasswordfromApp, "3. Request Change Password from App")
Rel_D(ChangePasswordfromApp, getUserBengkelbyBengkelID, "4. Request Get user bengkel data by Bengkel ID")
Rel_D(ChangePasswordfromApp, updatePassword, "6. Request Update Password")

Rel_D(getUserBengkelbyBengkelID, database, "5. Get user bengkel data by Bengkel ID")
Rel_D(updatePassword, database, "7. Update Password")

@enduml