@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title delete moadmin notif API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "delete moadmin notif API\n[Component]"){
Component(auths_middleware, "auth.verify", "Middleware | NodeJs", "Middleware for verify\n(NodeJs User API)")
Component(user_controller, "Moadmin Notif Controller", "Controller | NodeJs", "Controller for Moadmin Notif Related function\n(NodeJs User API)")
Component(delete, "MoadminNotif.delete", "Function | NodeJs", "Function for delete moadmin notif data\n(NodeJs User API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auths_middleware, "1. Request delete moadmin notif data")
Rel_D(auths_middleware, user_controller, "2. Request delete moadmin notif data")
Rel_D(user_controller, delete, "3. Request delete moadmin notif data")

Rel_D(delete, database, "4. delete moadmin notif data")

@enduml