@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title login workshop API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "login workshop API\n[Component]"){
Component(user_controller, "User Workshop Controller", "Controller | NodeJs", "Controller for User Workshop Related function\n(NodeJs User API)")
Component(logins, "UsersWorkshop.login", "Function | NodeJs", "Function for login\n(NodeJs User API)")
Component(login, "login", "Function | NodeJs", "Function for store login data\n(NodeJs User API)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, user_controller, "1. Request login")
Rel_D(user_controller, login, "2. Request login")
Rel_D(login, logins, "3. Request Store login data")
Rel_D(logins, database, "4. Store login data")

@enduml