@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title readAll OTP Request API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "readAll OTP Request API\n[Component]"){
Component(auths_middleware, "auth.verify", "Middleware | NodeJs", "Middleware for verify\n(NodeJs User API)")
Component(user_controller, "Management OTP Controller", "Controller | NodeJs", "Controller for Management OTP Related function\n(NodeJs User API)")
Component(readAll, "modelManagementOtp.readAll", "Function | NodeJs", "Function for Read All otp data\n(NodeJs User API)")
Component(countList, "modelManagementOtp.countList", "Function | NodeJs", "Function for count List otp data\n(NodeJs User API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auths_middleware, "1. Request Read All otp data")
Rel_D(auths_middleware, user_controller, "2. Request Read All otp data")
Rel_D(user_controller, readAll, "3. Request Read All otp data")
Rel_D(readAll, countList, "5. Request Count listy otp data")

Rel_D(readAll, database, "4. Read All otp data")
Rel_D(countList, database, "6. Count List otp data")

@enduml