@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title requestResetPassword2 API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "requestResetPassword2 API\n[Component]"){
Component(pass_controller, "Bengkel Pass Controller", "Controller | NodeJs", "Controller for Bengkel Pass Related function\n(NodeJs User API)")
Component(requestResetPassword2, "requestResetPassword2", "Function | NodeJs", "Function for request Reset Password\n(NodeJs User API)")
Component(readByEmailOrOwnerPhone, "UsersWorkshop.readByEmailOrOwnerPhone", "Function | NodeJs", "Function for read By Email Or Owner Phone\n(NodeJs User API)")

Component(token_creation, "token_creation", "Function | NodeJs", "Function for create token\n(NodeJs User API)")
Component(readByCode, "Reset_Pass.readByCode", "Function | NodeJs", "Function for read by Code\n(NodeJs User API)")
Component(InsertRequest, "Reset_Pass.InsertRequest", "Function | NodeJs", "Function for Insert Request\n(NodeJs User API)")
Component(sendEmail, "message.sendEmail", "Function | NodeJs", "Function for send Email\n(NodeJs User API)")
Component(sendMail, "transporter.sendMail", "Function | NodeJs", "Function for send Mail\n(NodeJs User API)")
Component(updateStatus, "Reset_Pass.updateStatus", "Function | NodeJs", "Function for update Status\n(NodeJs User API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Lay_D(sendMail, database)

Rel_D(Web_Moservice, pass_controller, "1. Request reset password")
Rel_D(pass_controller, requestResetPassword2, "2. Request reset password")

Rel_D(requestResetPassword2, readByEmailOrOwnerPhone, "3. Request Read user data by Email or Owner Phone")
Rel_D(requestResetPassword2, token_creation, "5. Create Token")
Rel_D(requestResetPassword2, readByCode, "6. Request Read data by Code")
Rel_D(requestResetPassword2, InsertRequest, "8. Request Insert Request data")
Rel_D(requestResetPassword2, sendEmail, "10. Request Send Email")
Rel_D(sendEmail, sendMail, "11. Send Email")
Rel_D(requestResetPassword2, updateStatus, "12. Update Status data")

Rel_D(readByEmailOrOwnerPhone, database, "4. Read user data by Email or Owner Phone")
Rel_D(readByCode, database, "7. Read data by Code")
Rel_D(InsertRequest, database, "9. Insert Request data")
Rel_D(updateStatus, database, "13. Update Request data")

@enduml