@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title ResetPassword API\n[NodeJs User API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "ResetPassword API\n[Component]"){
Component(pass_controller, "Bengkel Pass Controller", "Controller | NodeJs", "Controller for Bengkel Pass Related function\n(NodeJs User API)")
Component(ResetPassword, "ResetPassword", "Function | NodeJs", "Function for Reset Password\n(NodeJs User API)")

Component(readByCode, "Reset_Pass.readByCode", "Function | NodeJs", "Function for read by Code\n(NodeJs User API)")
Component(updatePassword, "UsersWorkshop.updatePassword", "Function | NodeJs", "Function for update Password\n(NodeJs User API)")
Component(updateStatus, "Reset_Pass.updateStatus", "Function | NodeJs", "Function for update Status\n(NodeJs User API)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, pass_controller, "1. Request Reset Password")
Rel_D(pass_controller, ResetPassword, "2. Request Reset Password")
Rel_D(ResetPassword, readByCode, "3. Request read by code")
Rel_D(ResetPassword, updatePassword, "5. Request update password")
Rel_D(ResetPassword, updateStatus, "7. Request update status")

Rel_D(readByCode, database, "4. Read by code")
Rel_D(updatePassword, database, "6. Update Password")
Rel_D(updateStatus, database, "8. Update Status")

@enduml