@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getYears API\n[mos-mobil-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "getYears API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-mobil-service)")
Component(loggerMiddleware, "Logger Middleware", "Middleware | TypeScript", "Logger Middleware for Moservice.id\n(mos-mobil-service)")

Component(mobils_controller, "Mobil Controller", "Controller | TypeScript", "Controller for Mobil Related Function\n(mos-mobil-service)")
Component(getYears, "getYears", "Function | TypeScript", "Main Function for Get Years List\n(mos-mobil-service)")
}
Rel_D(Web_Moservice, loggerMiddleware, "1. Request get years list")
Rel_D(loggerMiddleware, mainMiddleware, "2. Request get years list")

Rel_D(mainMiddleware, mobils_controller, "3. Request get years list")
Rel_D(mobils_controller, getYears, "4. Get Year list")

@enduml