@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Adiraku APP API (ms-account)

Container(adirakuAPP, "Adiraku APP", "Mobile App | React Native", "The main interface that the customer interacts with Adiraku")

System_Boundary(APIsystem, "API System") {
    AddProperty("url", "/api/v1/account/ktp")
    Component(ktp, "Validate KTP API", "Microservices | NodeJS", "Validate KTP")
    AddProperty("url", "/api/v1/account/tnc-save-historical")
    Component(tncHistorical, "Save TNC API", "Microservices | NodeJS", "Save TNC History")
    AddProperty("url", "/api/v1/account/inquiry-limit-lme")
    Component(inquiryLimitLME, "Inquiry Limit LME API", "Microservices | NodeJS", "Inquiry Limit LME")
    AddProperty("url", "/api/v1/account/change-mobile-number-v2")
    Component(changeMobileNumber, "Change mobile number API", "Microservices | NodeJS", "Change Mobile Number")
    AddProperty("url", "/api/v1/account/")
    AddProperty("method", "GET")
    Component(getAccount, "Get Account API", "Microservices | NodeJS", "Get Account")
    AddProperty("url", "/api/v1/account/")
    AddProperty("method", "POST")
    Component(postAccount, "Get Account API", "Microservices | NodeJS", "Get Account")
    AddProperty("url", "/api/v1/account/upload-profile-picture")
    Component(uploadProfPict, "Upload Prof Pict API", "Microservices | NodeJS", "Upload Profile Picture")
    AddProperty("url", "/api/v1/account/remove-profile-picture")
    Component(removeProfPict, "Remove Profile Picture API", "Microservices | NodeJS", "Remove Profile Picture")
    AddProperty("url", "/api/v1/account/change-email-address")
    Component(changeEmailAddress, "Change Email Address API", "Microservices | NodeJS", "Change Email Address")
    AddProperty("url", "/api/v1/account/update-pin")
    Component(updatePIN, "Update PIN API", "Microservices | NodeJS", "Update PIN")
    AddProperty("url", "/api/v1/account/contract-list")
    Component(contractList, "Contract List API", "Microservices | NodeJS", "List Contract")
    AddProperty("url", "/api/v1/account/send-email")
    Component(tanyaKami, "Tanya Kami API", "Microservices | NodeJS", "Send Email Tanya Kami")
    AddProperty("url", "/api/v1/account/bank-account")
    AddProperty("method", "GET")
    Component(getBankAccount, "Get Data Rekening API", "Microservices | NodeJS", "Get data rekening")
    AddProperty("url", "/api/v1/account/bank-account")
    AddProperty("method", "POST")
    Component(postBankAccount, "Create Data Rekening API", "Microservices | NodeJS", "Create data rekening")
    AddProperty("url", "/api/v1/account/bank-account")
    AddProperty("method", "PATCH")
    Component(patchBankAccount, "Update Data Rekening API", "Microservices | NodeJS", "Update data rekening")
    AddProperty("url", "/api/v1/account/bank-account")
    AddProperty("method", "DELETE")
    Component(deleteBankAccount, "Delete Data Rekening API", "Microservices | NodeJS", "Delete data rekening")
    AddProperty("url", "/api/v1/account/eligible-withdrawal")
    Component(eligibleWithdraw, "Eligible Withdrawal API", "Microservices | NodeJS", "Eligible Withdrawal")
    AddProperty("url", "/api/v1/account/validate-danamon-account")
    Component(validateDanamonAccount, "Validate Danamon Account API", "Microservices | NodeJS", "Validate Danamon Account")

    ComponentDb(Database, "Adiraku Storage", "mysql database, redis", "All store for save data and content")
}

Rel(adirakuAPP, ktp, "check ktp")
Rel(adirakuAPP, tncHistorical, "Save TNC")
Rel(adirakuAPP, inquiryLimitLME, "Inquiry Limit LME")
Rel(adirakuAPP, changeMobileNumber, "Change Mobile Number")
Rel(adirakuAPP, getAccount, "Get Account Detail")
Rel(adirakuAPP, postAccount, "Get Account Detail")
Rel(adirakuAPP, uploadProfPict, "Upload Profile Pict")
Rel(adirakuAPP, removeProfPict, "Remove Profile Picture")
Rel(adirakuAPP, changeEmailAddress, "Change Email Address")
Rel(adirakuAPP, updatePIN, "Update PIN")
Rel(adirakuAPP, contractList, "List Contract")
Rel(adirakuAPP, tanyaKami, "Send Email Tanya Kami")
Rel(adirakuAPP, getBankAccount, "Get data rekening")
Rel(adirakuAPP, postBankAccount, "Create data rekening")
Rel(adirakuAPP, patchBankAccount, "Update data rekening")
Rel(adirakuAPP, deleteBankAccount, "Delete data rekening")
Rel(adirakuAPP, eligibleWithdraw, "Eligible Withdrawal")
Rel(adirakuAPP, validateDanamonAccount, "Validate Danamon Account")


Rel(ktp, Database, "Crud Operation")
Rel(tncHistorical, Database, "Crud Operation")
Rel(inquiryLimitLME, Database, "Crud Operation")
Rel(changeMobileNumber, Database, "Crud Operation")
Rel(getAccount, Database, "Crud Operation")
Rel(postAccount, Database, "Crud Operation")
Rel(uploadProfPict, Database, "Crud Operation")
Rel(removeProfPict, Database, "Crud Operation")
Rel(changeEmailAddress, Database, "Crud Operation")
Rel(updatePIN, Database, "Crud Operation")
Rel(contractList, Database, "Crud Operation")
Rel(tanyaKami, Database, "Crud Operation")
Rel(getBankAccount, Database, "Crud Operation")
Rel(postBankAccount, Database, "Crud Operation")
Rel(patchBankAccount, Database, "Crud Operation")
Rel(deleteBankAccount, Database, "Crud Operation")
Rel(eligibleWithdraw, Database, "Crud Operation")
Rel(validateDanamonAccount, Database, "Crud Operation")

SHOW_LEGEND()

@enduml
