@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title disbursement API\n[mos-payment-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "disbursement API\n[Component]"){
Component(loggerMiddleware, "Logger Middleware", "Middleware | TypeScript", "Logger Middleware for Moservice.id\n(mos-payment-service)")

Component(auth_operator_middleware, "Auth Operator Middleware", "Middleware | TypeScript", "Middleware for Operator Authentication\n(mos-payment-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-payment-service)")
Component(disbursement_controller, "Disbursement Controller", "Controller | TypeScript", "Controller for Disbursement Related Function\n(mos-payment-service)")
Component(disbursement, "disbursement", "Function | TypeScript", "Function for disbursement\n(mos-payment-service)")
Component(checkDisbursementAlreadyRun, "DisbursementRepository.findOne", "Function | TypeScript", "Function for disbursement\n(mos-payment-service)")
Component(runDisbursement, "runDisbursement", "Function | TypeScript", "Function for run disbursement\n(mos-payment-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

AddProperty("Repository", "mos-auth-service")
AddProperty("URL", "/api/admin/authenticate")
Component(authenticateAdmin, "authenticateAdmin", "Function | TypeScript", "Function for Authentication Admin\")

AddProperty("Topic", "moservice-disbursement-manually")
SystemQueue(Kafka, "Kafka")
Rel_D(Web_Moservice, mainMiddleware, "1. Request disbursement")
Rel_D(mainMiddleware, loggerMiddleware, "2. Request disbursement")

Rel_D(loggerMiddleware, auth_operator_middleware, "3. Request disbursement")
Rel_L(auth_operator_middleware, authenticateAdmin, "4. Request disbursement")
Rel_D(auth_operator_middleware, disbursement_controller, "5. Request disbursement")
Rel_D(disbursement_controller, disbursement, "6. Request check disbursement")
Rel_D(disbursement, checkDisbursementAlreadyRun, "7. Request check disbursement data")
Rel_D(disbursement, runDisbursement, "9. Request Run Disbursement")
Rel_D(runDisbursement, Kafka, "10. Request Send Notification")
Rel_D(checkDisbursementAlreadyRun, database, "8. Check disbursement data")


@enduml