@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title show merchant configuration API\n[mos-payment-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "show merchant configuration API\n[Component]"){
Component(loggerMiddleware, "Logger Middleware", "Middleware | TypeScript", "Logger Middleware for Moservice.id\n(mos-payment-service)")

Component(server_auth_middleware, "Server Auth Middleware", "Middleware | TypeScript", "Middleware for server Authentication\n(mos-payment-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-payment-service)")
Component(payment_merchant_config_controller, "Payment Merchant Config Controller", "Controller | TypeScript", "Controller for Payment Merchant Config Related Function\n(mos-payment-service)")
Component(show, "show", "Function | TypeScript", "Function for show payment merchant config data\n(mos-payment-service)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, mainMiddleware, "1. Request show payment merchant config data")
Rel_D(mainMiddleware, loggerMiddleware, "2. Request show payment merchant config data")

Rel_D(loggerMiddleware, server_auth_middleware, "3. Request show payment merchant config data")
Rel_D(server_auth_middleware, payment_merchant_config_controller, "4. Request show payment merchant config data")
Rel_D(payment_merchant_config_controller, show, "5. Request show payment merchant config data")
Rel_D(show, database, "6. Retrieve payment merchant config data")


@enduml