@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title getBrand API 

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services")
    
    Boundary(api, "getBrand API\n[Component]"){
        
        Component(getBrand, "getBrand", "Function | NodeJS", "API for Get New Motorcycle Brand data\n{ms-auth}")

    }
    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, getBrand, "1. Send request Get New Motorcycle Brand data")
Rel_D(getBrand, momo_x_storage, "2. Retrieve & Find New Motorcycle Brand data")


SHOW_LEGEND()
@enduml