@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title markRead API\n[mos-notification-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "markRead API\n[Component]"){
Component(auth_operator_middleware, "Auth Operator Middleware", "Middleware | TypeScript", "Middleware for Operator Authentication\n(mos-notification-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-notification-service)")




Component(operator_notification_controller, "Operator Notification Controller", "Controller | TypeScript", "Controller for Operator Notification Function\n(mos-notification-service)")
Component(markRead, "markRead", "Function | TypeScript", "Function for Update Mark Read Notification Status\n(mos-notification-service)")
Component(updateNotifRepo, "MapOperatorNotificationRepository.update", "Function | TypeScript", "Function for Update Mark Read Notification Status\n(mos-notification-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
AddProperty("Repository", "mos-auth-service")
AddProperty("URL", "/api/admin/authenticate")
Component(MosAuthService, "MosAuthService.authenticateAdmin", "Middleware | TypeScript", "Function For Authenticate Admin by using xToken\n(mos-auth-service)")

Rel_D(Web_Moservice, mainMiddleware, "1. Request Operator Notification")
Rel_D(mainMiddleware, auth_operator_middleware, "2. Request Operator Notification")

Rel_L(auth_operator_middleware, MosAuthService, "3. Admin Verification")
Rel_D(auth_operator_middleware, operator_notification_controller, "4. Request Update Markread Status")
Rel_D(operator_notification_controller, markRead, "5. Request Update Markread Status")
Rel_D(markRead, updateNotifRepo, "6. Update Markread Status")
Rel_R(updateNotifRepo, database, "7. Update Markread Status")

@enduml