@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title changePassword Admin\n[changePassword]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Admin")
    
    Boundary(api, "changePassword API\n[Component]"){
        
        Component(auth_middleware, "verifyChangePasswordAdmin", "Middleware | NodeJS", "Middleware for check request body and token API change password admin\n{ms-auth}")
        Component(changePassword, "changePassword", "Function | NodeJS", "API for changePassword Admin\n{ms-auth}")

    }

    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware, "1. Send request changePassword Admin and check request body")
Rel_D(auth_middleware, changePassword, "2. Send request changePassword Admin")
Rel_D(changePassword, momo_x_storage, "3. Validate auth_id Admin")
Rel_D(changePassword, momo_x_storage, "4. Update password Admin")
Rel_D(changePassword, momo_x_storage, "5. Insert log change password Admin")

SHOW_LEGEND()
@enduml