@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


LAYOUT_WITH_LEGEND()
title Login Admin\n[login]

    Container(web_momo_x, "Web Momo X", "Website | NextJS", "Momo main services for Admin")
    
    Boundary(api, "login API\n[Component]"){

        Component(auth_middleware, "verifyLoginAdmin", "Middleware | NodeJS", "Middleware for check request body and token API login admin\n{ms-auth}")
        Component(login, "login", "Function | NodeJS", "API for login Admin\n{ms-auth}")

    }

    ContainerDb(momo_x_storage, "Momo X Database", "MySql Database", "Storage Database for auth momo x")


Rel_D(web_momo_x, auth_middleware, "1. Send request login Admin and check request body")
Rel_D(auth_middleware, login, "2. Send request login Admin")
Rel_D(login, momo_x_storage, "3. Validate email & password Admin")
Rel_D(login, momo_x_storage, "4. Insert session login Admin")
Rel_D(login, momo_x_storage, "5. Insert log login Admin")

SHOW_LEGEND()
@enduml