@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Clear Session API (/api/v1/auth/clear-session)

AddProperty("repository", "MS-Account")
AddProperty("method", "PATCH")
AddProperty("url", "/api/v1/account/mobile-number")
Container(updateMobileNumber, "Update Mobile Number API", "microservices | NodeJS", "API update mobile number from admin panel")

AddProperty("repository", "MS-Account")
AddProperty("method", "PUT")
AddProperty("url", "/api/v1/account/mobile-number")
Container(updateMobileNumber2, "Update Mobile Number API", "microservices | NodeJS", "API update mobile number from admin panel")

System_Boundary(clearSessionAPI, "Clear Session API") {
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller")
}
ContainerDb(database, "Adiraku Storage", "mysql", "adr_auth_otp")

Rel(updateMobileNumber, controller, "1. API call [JSON/HTTPS]")
Rel(updateMobileNumber2, controller, "1. API call [JSON/HTTPS]")
Rel(controller, database, "2. Delete mobile number data")
SHOW_LEGEND()
@enduml
