@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Generate OTP Email Prospect API (/api/v1/auth/generate-email-otp-prospect)

Container(adirakuAPP, "Adiraku APP", "Mobile App | React Native", "The main interface that the customer interacts with Adiraku")

System_Boundary(generateOTPEmail, "Generate OTP Email API") {
    Component(verifyToken, "Verify Token", "Function", "Verify Token Auth")
    Boundary(verifyTokenAuth, "verify token auth") {
        Component(verify, "Verify Token", "Function", "Verify JWT Token")
        Component(decrypt, "Decrypt Data", "Function", "Decrypt Data Decoded Token")
        Component(encrypt, "Encrypt Data", "Function", "Encrypt Data")
        Component(jwt, "Sign JWT", "Function", "Sign JWT")
    }
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller")
}

AddProperty("repository", "MS-Loyalty")
AddProperty("method", "POST")
AddProperty("url", "/api/v1/get-account-prospect")
Component(getAccountProspectAPI, "Get Account Prospect API", "microservices | NodeJS", "Check Account Prospect")

System_Ext(generateOTP, "Generate OTP", "Library")
System_Ext(email, "Send Grid Email", "Library")

ContainerDb(database, "Adiraku Storage", "mysql", "adr_auth_otp")

Rel(adirakuAPP, verifyToken, "1. API Call [JSON/HTTPS]")
Rel(verifyToken, verify, "2. Send Token, Verify Token")
Rel(verify, decrypt, "2a. Decrypt data token")
Rel(decrypt, encrypt, "2b. Encrypt new data")
Rel(encrypt, jwt, "2c. Create new JWT")
Rel(verifyToken, controller, "3. Send request data")
Rel(controller, getAccountProspectAPI, "4. Check data")
Rel(getAccountProspectAPI, generateOTP, "5. Generate OTP")
Rel(getAccountProspectAPI, database, "6. CRUD Request")
Rel(getAccountProspectAPI, email, "7. Send Email")

SHOW_LEGEND()

@enduml
