@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Logout API (/api/v1/auth/logout)

Container(adirakuAPP, "Adiraku APP", "Mobile App | React Native", "The main interface that the customer interacts with Adiraku")

System_Boundary(logoutAPI, "Logout API") {
    Component(verifyToken, "Verify Token", "Function", "Verify Token Auth")
    Boundary(verifyTokenAuth, "verify token auth") {
        Component(verify, "Verify Token", "Function", "Verify JWT Token")
        Component(decrypt, "Decrypt Data", "Function", "Decrypt Data Decoded Token")
        Component(encrypt, "Encrypt Data", "Function", "Encrypt Data")
        Component(jwt, "Sign JWT", "Function", "Sign JWT")
    }
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller")
}

AddProperty("repository", "MS-Account")
AddProperty("url", "/api/v1/account/get-account-by")
Component(getAccountAPI, "Get Account API", "microservices | NodeJS", "Check Account")

ContainerDb(database, "Adiraku Storage", "mysql", "adr_auth_otp")

AddProperty("repository", "MS-Account")
AddProperty("url", "/api/v1/account/post-account-by")
Component(updateAccountAPI, "Update Account API", "microservices | NodeJS", "Update Account")

SystemDb_Ext(firestore, "firestore", "data session")

Rel(adirakuAPP, verifyToken, "1. API Call [JSON/HTTPS]")
Rel(verifyToken, verify, "2. Send Token, Verify Token")
Rel(verify, decrypt, "2a. Decrypt data token")
Rel(decrypt, encrypt, "2b. Encrypt new data")
Rel(encrypt, jwt, "2c. Create new JWT")
Rel(verifyToken, controller, "3. Send request data")
Rel(controller, getAccountAPI, "4. Check Account")
Rel(getAccountAPI, database, "5. Update Session")
Rel(getAccountAPI, updateAccountAPI, "6. Update Device ID")
Rel(updateAccountAPI, firestore, "7. Update data session")

@enduml
