@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Validate OTP Vdata (/api/v1/auth/validate-otp-vdata)

Container(adirakuAPP, "Adiraku APP", "Mobile App | React Native", "The main interface that the customer interacts with Adiraku")

System_Boundary(validateOTPAPI, "Generate OTP API") {
    Component(verifyToken, "Verify Token", "Function", "Verify Token Mobile Number")
    Boundary(verifyTokenMobile, "verify token") {
        Component(verify, "Verify Token", "Function", "Verify JWT Token")
        Component(decrypt, "Decrypt Data", "Function", "Decrypt Data Decoded Token")
        Component(encrypt, "Encrypt Data", "Function", "Encrypt Data")
        Component(jwt, "Sign JWT", "Function", "Sign JWT")
    }
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller")
}

ContainerDb(database, "Adiraku Storage", "mysql", "adr_auth_otp")

Rel(adirakuAPP, verifyToken, "1. API Call [JSON/HTTPS]")
Rel(verifyToken, verify, "2. Verify Token")
Rel(verify, decrypt, "2a. Decrypt decoded data")
Rel(decrypt, encrypt, "2b. Encrypt new data")
Rel(encrypt, jwt, "2c. Sign JWT new data")
Rel(verifyToken, controller, "3. Send request data")
Rel(controller, database, "4. Read / Update OTP")

@enduml
