@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title Component Diagram for Admin Update Product data\n (api/v1/micro-insurance/admin/product-update)
Container(adiraku, "Akses Admin Panel BE", "Repository | NodeJs", "Admin Panel Backend Repository for Adiraku Function (updatetolist)")

Boundary(api, "Admin Product Update API\n[Component]"){
    AddProperty("Path", "ms-insurance\api\v1\micro-insurance\controller.js")
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller for Micro Insurance Related Function")
    Component(verifyTokenAdmPanel, "utils.verifyTokenAdmPanel", "Function | NodeJs", "Function for Verify Token from Admin Panel")

    Component(adminProductUpdate, "adminProductUpdate", "Function | NodeJs", "Function for Admin Update Product data")
    
}    
ContainerDb(database, "Adiraku Storage", "mySql Database", "AdrMicroProduct")

Rel(adiraku, verifyTokenAdmPanel, "1. Verify Token Admin Panel")
Rel(verifyTokenAdmPanel, controller, "2. Request Admin Update Product data")
Rel(controller, adminProductUpdate, "3. Request Admin Update Product data")
Rel(adminProductUpdate, database, "4. Check data Update\n(AdrMicroProduct)\ndata")
Rel(adminProductUpdate, database, "5. if(checkDataUpdate.product_code != product_code_konvensional)\n=\nCheck Product Code (AdrMicroProduct)\ndata")
Rel(adminProductUpdate, database, "6. Update\n(AdrMicroProduct)\ndata")

@enduml