@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title setPrimary API\n[NodeJs Mobil API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "setPrimary API\n[Component]"){
Component(auth_middleware, "auth.validate", "Middleware | NodeJs", "Authentication Middleware for validate Function\n(NodeJs Mobil API)")
Component(mobil_controller, "Mobil Controller", "Controller | NodeJs", "Controller for Mobil Related Function\n(NodeJs Mobil API)")
Component(setPrimary, "setPrimary", "Function | NodeJs", "Function for set primary vehicle\n(NodeJs Mobil API)")
Component(setPrimarys, "Mobil.setPrimary", "Function | NodeJs", "Function for update data\n(NodeJs Mobil API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request update primary vehicle data by car ID")
Rel_D(auth_middleware, mobil_controller, "2. Request update primary vehicle data by car ID")
Rel_D(mobil_controller, setPrimary, "3. Request update primary vehicle data by car ID")
Rel_D(setPrimary, setPrimarys, "4. Set Primary vehicle data by car ID")
Rel_D(setPrimarys, database, "5. Update primary vehicle data by car ID")

@enduml