@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title Component Diagram for Channel push Notification\n (api/v1/notification/channel-push-notification)

AddProperty("URL", "process.env.MS_AUTH_URL + '/channel/token/verify'")
AddProperty("Repository", "ms-auth")
Component(verifyChannelBearerToken, "verifyChannelBearerToken", "Middleware | NodeJs", "Middleware for Verify Channel Bearer Token")

Boundary(api, "channelNotification API\n[Component]"){
    AddProperty("Path", "ms-notification\api\v1\Notification\controller.js")
    Component(controller, "Controller", "NodeJS MVC Controller", "Main Controller for Notification Related Function")

    Component(channelNotification, "channelNotification", "Function | NodeJs", "Function for Channel push Notification")
}
AddProperty("URL", "process.env.MS_ACCOUNT_BASE_URL + '/account/get-account-by'")
AddProperty("Repository", "ms-account")
Component(getAccountBy, "getAccountBy", "Function | NodeJs", "Function for Get Account")

AddProperty("URL", "process.env.MS_ACTIVITY_URL + '/activity'")
AddProperty("Repository", "ms-activity")
Component(activity, "activity", "Function | NodeJs", "Function for Create Activity")

AddProperty("URL", "http://localhost:${process.env.PORT}/api/v1/notification-insider/request-notification")
AddProperty("Repository", "ms-notification")
Component(requestPushNotification, "requestPushNotification", "Function | NodeJs", "Function for Request Push Notification")

Rel(verifyChannelBearerToken, controller, "2. Request Channel push Notification")

Rel(controller, channelNotification, "3. Request Channel push Notification")
Rel(channelNotification, getAccountBy, "4. Retrieve resultAccount data")
Rel(channelNotification, activity, "5. Create Activity")
Rel(channelNotification, requestPushNotification, "6. Request Push Notification (messageNotification)")

@enduml