@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title findQrById API\n[mos-content-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "findQrById API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-content-service)")

Component(auth_middleware, "Auth Middleware", "Middleware | TypeScript", "Middleware for Authentication\n(mos-content-service)")
Component(auth_middlewares, "Auth Operator Middleware", "Middleware | TypeScript", "Middleware for Operator Authentication\n(mos-content-service)")
Component(getPemKey, "getPemKey", "Function | TypeScript", "Function for Get Pemkey\n(mos-content-service)")

Component(qr_controller, "QR Controller", "Controller | TypeScript", "Controller for QR Function Related\n(mos-content-service)")
Component(findQrById, "findQrById", "Function | TypeScript", "Main Function for Find QR data by ID\n(mos-content-service)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, mainMiddleware, "1. Request Find QR Data by ID")

Rel_D(mainMiddleware, auth_middleware, "2. Request Find QR Data by ID")
Rel_L(auth_middleware, auth_middlewares, "3. If there is (xToken), Return Auth Operator Middleware.")

Rel_R(auth_middleware, getPemKey, "3. Else, Get Pem Key")
Rel_D(auth_middleware, qr_controller, "4. Request Find QR Data by ID")
Rel_D(auth_middlewares, qr_controller, "4. Request Find QR Data by ID")

Rel_D(qr_controller, findQrById, "4. Request Find QR Data by ID")
Rel_D(findQrById, database, "5. Search & Retrieve QR Data by ID")

@enduml