@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title index Banner API\n[mos-content-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "index Banner API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-content-service)")

Component(banner_controller, "Banner Controller", "Controller | TypeScript", "Controller for Banner Related Function\n(mos-content-service)")
Component(index, "index", "Function | TypeScript", "Main Function for get banner list data\n(mos-content-service)")
}
ContainerDb(Redis, "Redis", ,"External System For Store Cache & Database")
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, mainMiddleware, "1. Request get banner list data")

Rel_D(mainMiddleware, banner_controller, "2. Request get banner list data")
Rel_D(banner_controller, index, "3. Request get banner list data")
Rel_D(index, Redis, "4. Retrieve banner list data")
Rel_R(index, database, "5. Retrieve banner list data")


@enduml