@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for

AddProperty("repository", "MS-Authentication")
AddProperty("url", "/api/v1/auth/reset-pin-v2")
Container(resetPINV2, "Reset PIN API", "Microservices | NodeJS", "Reset PIN Adiraku")

AddProperty("repository", "MS-Authentication")
AddProperty("url", "/api/v1/auth/verify-token-prospect")
Container(verifyTokenProspectAPI, "Verify Token Prospect API", "Microservices | NodeJS", "Verify Token Prospect API")

AddProperty("repository", "MS-Authentication")
AddProperty("url", "/api/v1/auth/find-mobile-number-login")
Container(findMobileNumberLoginAPI, "Find Mobile Number Login API", "Microservices | NodeJS", "Find Mobile Number for Login")

AddProperty("repository", "MS-Authentication")
AddProperty("url", "/api/v1/auth/find-mobile-number-v2")
Container(findMobileNumberV2API, "Find Mobile Number V2 API", "Microservices | NodeJS", "Find Mobile Number for Register")

@enduml
