@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Create Token Channel API (/api/v1/channel/token)

AddProperty("repository", "MS-Authentication")
AddProperty("url", "/api/v1/channel/token")
Container(authAPI, "Auth Channel Token API", "microservices | NodeJS", "API for create token channel")


SHOW_LEGEND()

@enduml
