@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title listOrderDownloadReport API\n[NodeJs Booking API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "listOrderDownloadReport API\n[Component]"){
Component(auth_middleware, "Auth.validateBengkelId", "Middleware | NodeJs", "Authentication Middleware for Validate Bengkel ID\n(NodeJs Booking API)")
Component(booking_order_controller, "Booking Order Controller", "Controller | NodeJs", "Controller for Booking Order Related Function\n(NodeJs Booking API)")
Component(listOrder, "listOrderDownloadReport", "Function | NodeJs", "Function for download list order report\n(NodeJs Booking API)")
Component(countFilterDownloadReport, "Booking_Order.countFilterDownloadReport", "Function | NodeJs", "Function for count filter download report\n(NodeJs Booking API)")
Component(filterDownloadReport, "Booking_Order.filterDownloadReport", "Function | NodeJs", "Function for filter download report\n(NodeJs Booking API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, auth_middleware, "1. Request retrieve list order download report")
Rel_D(auth_middleware, booking_order_controller, "2. Request retrieve list order download report")
Rel_D(booking_order_controller, listOrder, "3. Request Retrieve list order download report")
Rel_D(listOrder, countFilterDownloadReport, "4. Request Count dowload report data")
Rel_D(listOrder, filterDownloadReport, "6. Request Filter download report data")

Rel_D(countFilterDownloadReport, database, "5. Count download report")
Rel_D(filterDownloadReport, database, "7. Filter download report")

@enduml