@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title orderDetailByBookingID API\n[NodeJs Booking API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "orderDetailByBookingID API\n[Component]"){
Component(booking_order_controller, "Booking Order Controller", "Controller | NodeJs", "Controller for Booking Order Related Function\n(NodeJs Booking API)")
Component(orderDetailByBookingID, "orderDetailByBookingID", "Function | NodeJs", "Function for retrieve order detail by booking ID\n(NodeJs Booking API)")
Component(readByIDWithAdditionalData, "readByIDWithAdditionalData", "Function | NodeJs", "Function for read ID with Additional Data \n(NodeJs Booking API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")


Rel_D(Web_Moservice, booking_order_controller, "1. Request retrieve order detail by booking ID")
Rel_D(booking_order_controller, orderDetailByBookingID, "2. Request retrieve order detail by booking ID")
Rel_D(orderDetailByBookingID, readByIDWithAdditionalData, "3. Request retrieve order detail by booking ID")
Rel_D(readByIDWithAdditionalData, database, "4. Retrieve order detail by booking ID")





@enduml