@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title NodeJs Service Platform Booking API

Component(Web_Moservice, "API Gateway", "Services | TypeScript", "All API used by moservice.id")
Component(API, "NodeJs Service Platform Booking API", "Repository | NodeJs", "Repository for NodeJs Booking Related Function")

Boundary(api, "NodeJs Booking API\n[Component]"){
Component(OTP, "OTP", "Function | TypeScript", "Function for Generate, Check OTP\n(NodeJs Booking API)")
Component(checkIsHourAvailable, "checkIsHourAvailable", "Function | NodeJs", "Function for Check is hour available\n(NodeJs Booking API)")
Component(createBooking, "Create Booking", "Function | NodeJs", "Function for Create Booking\n(NodeJs Booking API)")
Component(afterRegister, "afterRegister", "Function | NodeJs", "Function for Send email after register process\n(NodeJs Booking API)")
Component(createUpdatePreBooking, "Create Update PreBooking", "Function | NodeJs", "Function for Create Update Prebooking, Create Prebooking From Promo\n(NodeJs Booking API)")
Component(getHourByDate, "getHourByDate", "Function | NodeJs", "Function for Get hour by date\n(NodeJs Booking API)")
Component(getMultiConditionList, "getMultiConditionList", "Function | NodeJs", "Function for Get multi condition list Booking and Prebooking\n(NodeJs Booking API)")
Component(getCurrentActivityBengkel, "getCurrentActivityBengkel", "Function | NodeJs", "Function for Get bengkel current activity\n(NodeJs Booking API)")
Component(getValidBooking, "getValidBooking", "Function | NodeJs", "Function for Validate booking\n(NodeJs Booking API)")
Component(groupParamsByKey, "groupParamsByKey", "Function | NodeJs", "Function for Decode qr code\n(NodeJs Booking API)")
Component(insertMapBookingServices, "insertMapBookingService", "Function | NodeJs", "Function for Insert Map Booking Service\n(NodeJs Booking API)")
Component(listOrder, "List Order", "Function | NodeJs", "Function for Retrieve list order and Download Report data\n(NodeJs Booking API)")
Component(orderDetailByBookingID, "orderDetailByBookingID", "Function | NodeJs", "Function for Retrieve order detail by booking ID\n(NodeJs Booking API)")
Component(readByBookingID, "readByBookingID", "Function | NodeJs", "Function for Read booking by booking ID\n(NodeJs Booking API)")
Component(readByPrebookID, "readByPrebookID", "Function | NodeJs", "Function for Read prebooking data by prebooking ID\n(NodeJs Booking API)")
Component(readBySessionID, "readBySessionID", "Function | NodeJs", "Function for Read prebooking data by session ID\n(NodeJs Booking API)")
Component(readByUserID, "readByUserID", "Function | NodeJs", "Function for Read By User ID\n(NodeJs Booking API)")
Component(reschedule, "reschedule", "Function | NodeJs", "Function for Reschedule booking\n(NodeJs Booking API)")
Component(setBookingAvailability, "setBookingAvailability", "Function | NodeJs", "Function for Set booking availability\n(NodeJs Booking API)")
Component(updatePrebook, "Update Prebook", "Function | NodeJs", "Function for Update Prebook data, Update Prebook Note\n(NodeJs Booking API)")
Component(updateBookingMobilKM, "updateBookingMobilKM", "Function | NodeJs", "Function for Update Booking KM Mobil\n(NodeJs Booking API)")
}

ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel(Web_Moservice, API, "Request use function related to Booking")

Rel(API, OTP, "Request Generate, Check OTP")
Rel(API, checkIsHourAvailable, "Request Check is hour available")
Rel(API, createBooking, "Request Create Booking")
Rel(API, afterRegister, "Request Send email after register process")
Rel(API, createUpdatePreBooking, "Request Create Update Prebooking, Create Prebooking From Promo")
Rel(API, getHourByDate, "Request Get hour by date")
Rel(API, getMultiConditionList, "Request Get multi condition list Booking and Prebooking")
Rel(API, getCurrentActivityBengkel, "Request Get bengkel current activity")
Rel(API, getValidBooking, "Request Validate booking")
Rel(API, groupParamsByKey, "Request Decode qr code")
Rel(API, insertMapBookingServices, "Request Insert Map Booking Service")

Rel(API, listOrder, "Request Retrieve list order and Download Report data")
Rel(API, orderDetailByBookingID, "Request Retrieve order detail by booking ID")
Rel(API, readByBookingID, "Request Read booking by booking ID")
Rel(API, readByPrebookID, "Request Read prebooking data by prebooking ID")
Rel(API, readBySessionID, "Request Read prebooking data by session ID")
Rel(API, readByUserID, "Request Read by User ID")
Rel(API, reschedule, "Request Reschedule booking")
Rel(API, setBookingAvailability, "Request Set booking availability")
Rel(API, updatePrebook, "Request Update Prebook data, Update Prebook Note")
Rel(API, updateBookingMobilKM, "Request Update Booking KM Mobil")

Rel(OTP, database, "Generate, Check OTP")
Rel(checkIsHourAvailable, database, "Check is hour available")
Rel(createBooking, database, "Create Booking")
Rel(afterRegister, database, "Send email after register process")
Rel(createUpdatePreBooking, database, "Create Update Prebooking, Create Prebooking From Promo")
Rel(getHourByDate, database, "Get hour by date")
Rel(getMultiConditionList, database, "Get multi condition list Booking and Prebooking")
Rel(getCurrentActivityBengkel, database, "Get bengkel current activity")
Rel(getValidBooking, database, "Validate booking")
Rel(groupParamsByKey, database, "Decode qr code")
Rel(insertMapBookingServices, database, "Insert Map Booking Service")

Rel(listOrder, database, "Retrieve list order and Download Report data")
Rel(orderDetailByBookingID, database, "Retrieve order detail by booking ID")
Rel(readByBookingID, database, "Read booking by booking ID")
Rel(readByPrebookID, database, "Read prebooking data by prebooking ID")
Rel(readBySessionID, database, "Read prebooking data by session ID")
Rel(readByUserID, database, "Read by User ID")
Rel(reschedule, database, "Reschedule booking")
Rel(setBookingAvailability, database, "Set booking availability")
Rel(updatePrebook, database, "Update Prebook data, Update Prebook Note")
Rel(updateBookingMobilKM, database, "Update Booking KM Mobil")