@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title checkIsHourAvailable API\n[NodeJs Booking API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "checkIsHourAvailable API\n[Component]"){
Component(booking_order_controller, "Booking Order Controller", "Controller | NodeJs", "Controller for Booking Order Related Function\n(NodeJs Booking API)")
Component(checkIsHourAvailable, "checkIsHourAvailable", "Function | NodeJs", "Function for Check is hour available\n(NodeJs Booking API)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")


Rel_D(Web_Moservice, booking_order_controller, "1. Request Check is hour available")
Rel_D(booking_order_controller, checkIsHourAvailable, "2. Check is hour available")

Rel_D(checkIsHourAvailable, database, "3. Check is hour available")



@enduml