@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title readBySessionID API\n[NodeJs Booking API]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "readBySessionID API\n[Component]"){
Component(pre_booking_controller, "Prebooking Controller", "Controller | NodeJs", "Controller for Prebooking Related Function\n(NodeJs Booking API)")
Component(readBySessionID, "Pre_Booking.readBySessionID", "Function | NodeJs", "Function for read prebooking data by session ID\n(NodeJs Booking API)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, pre_booking_controller, "1. Request read prebooking data by session ID")
Rel_D(pre_booking_controller, readBySessionID, "2. Request read prebooking data by session ID")
Rel_D(readBySessionID, database, "3. Retrieve prebooking data by session ID")
@enduml