@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title detail Model API\n[mos-mobil-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "details Model API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-mobil-service)")
Component(loggerMiddleware, "Logger Middleware", "Middleware | TypeScript", "Logger Middleware for Moservice.id\n(mos-mobil-service)")

Component(spMoadminAuthMiddleware, "Sp Moadmin Auth Middleware", "Controller | TypeScript", "Middleware for Moadmin Authentication\n(mos-mobil-service)")
Component(sp_mobil_model_controller, "Sp Mobil Model Controller", "Controller | TypeScript", "Controller for Mobil Model Related Function\n(mos-mobil-service)")
Component(detail, "detail", "Function | TypeScript", "Main Function for Show Model data detail\n(mos-mobil-service)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, loggerMiddleware, "1. Request Show Car Model Data details by Model ID")
Rel_D(loggerMiddleware, mainMiddleware, "2. Request Show Car Model Data details by Model ID")

Rel_D(mainMiddleware, spMoadminAuthMiddleware, "3. Request Show Car Model Data details by Model ID")
Rel_D(spMoadminAuthMiddleware, sp_mobil_model_controller, "4. Request Show All Car Model Data details by Model ID")

Rel_D(sp_mobil_model_controller, detail, "5. Request Show All Car Model Data details by Model ID")
Rel_D(detail, database, "6. Search & Retrieve All Car Model Data details by Model ID")

@enduml