@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getCarTypes API\n[mos-mobil-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "getCarTypes API\n[Component]"){
Component(mobil_controller, "Mobil Controller", "Controller | TypeScript", "Controller for Mobil Related Function\n(mos-mobil-service)")
Component(getCarTypes, "getCarTypes", "Function | TypeScript", "Main Function for Get Car Types\n(mos-mobil-service)")
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-mobil-service)")
Component(loggerMiddleware, "Logger Middleware", "Middleware | TypeScript", "Logger Middleware for Moservice.id\n(mos-mobil-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, loggerMiddleware, "1. Request get car types Data")
Rel_D(loggerMiddleware, mainMiddleware, "2. Request get car types Data")

Rel_D(mainMiddleware, mobil_controller, "3. Request get car types Data")
Rel_D(mobil_controller, getCarTypes, "4. Request get car types Data")
Rel_D(getCarTypes, database, "5. Search & Retrieve Car Types Data")

@enduml