@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title index Brand API\n[mos-mobil-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "index Brand API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-mobil-service)")
Component(loggerMiddleware, "Logger Middleware", "Middleware | TypeScript", "Logger Middleware for Moservice.id\n(mos-mobil-service)")

Component(brand_controller, "Brand Controller", "Controller | TypeScript", "Controller for Brand Related Function\n(mos-mobil-service)")
Component(index, "Index", "Function | TypeScript", "Main Function for get all car brands\n(mos-mobil-service)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, loggerMiddleware, "1. Request All Car Brands")
Rel_D(loggerMiddleware, mainMiddleware, "2. Request All Car Brands")

Rel_D(mainMiddleware, brand_controller, "3. Request All Car Brands")
Rel_D(brand_controller, index, "4. Request All Car Brands Data")
Rel_D(index, database, "5. Search & Retrieve All Car Brands Data")

@enduml