@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title changePassword API\n[mos-user-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "changePassword API\n[Component]"){
Component(auth_middleware, "Auth Middleware", "Middleware | TypeScript", "Middleware for Authentication\n(mos-user-service)")
Component(getPemKey, "getPemKey", "Function | TypeScript", "Function for Get Pemkey\n(mos-user-service)")

Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-user-service)")
Component(user_controller, "User Controller", "Controller | TypeScript", "Controller for User Related Function\n(mos-user-service)")
Component(changePassword, "changePassword", "Function | TypeScript", "Function for change password\n(mos-user-service)")
Component(checkValidPassword, "checkValidPassword", "Function | TypeScript", "Function for check valid password\n(mos-user-service)")

}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")
Rel_D(Web_Moservice, mainMiddleware, "1. Request change password")

Rel_D(mainMiddleware, auth_middleware, "2. Request change password")
Rel_R(auth_middleware, getPemKey, "3. Get Pem key")

Rel_D(auth_middleware, user_controller, "4. Request change password")
Rel_D(user_controller, changePassword, "5. Request change password")
Rel_D(changePassword, checkValidPassword, "6. Check If Password is Valid")
Rel_D(checkValidPassword, database, "7. If password is valid, update password in database")

@enduml