@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title getCredential API\n[mos-user-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "getCredential API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-user-service)")
Component(auth_middleware, "Auth Middleware", "Middleware | TypeScript", "Middleware for Authentication\n(mos-user-service)")
Component(getPemKey, "getPemKey", "Function | TypeScript", "Function for Get Pemkey\n(mos-user-service)")

Component(user_controller, "User Controller", "Controller | TypeScript", "Controller for User Related Function\n(mos-user-service)")
Component(getCredential, "getCredential", "Function | TypeScript", "Function for get user credential data\n(mos-user-service)")
}
ContainerDb(database, "Moservice Storage", "mySQL Database", "All store for save data and content for Moservice.id")

Rel_D(Web_Moservice, mainMiddleware, "1. Request get user credential data")

Rel_D(mainMiddleware, auth_middleware, "2. Request get user credential data")
Rel_R(auth_middleware, getPemKey, "3. Request get user credential data")

Rel_D(auth_middleware, user_controller, "4. Request get user credential data")
Rel_D(user_controller, getCredential, "5. Get user credential data")
Rel_D(getCredential, database, "6. Get user credential data")

@enduml