@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()
title logout API\n[mos-user-service]
Container(Web_Moservice, "Web Moservice", "Website | JavaScript", "moservice.id main services for Customer")
Boundary(api, "logout API\n[Component]"){
Component(mainMiddleware, "Main Middleware", "Middleware | TypeScript", "Main Middleware for Moservice.id\n(mos-user-service)")
Component(auth_middleware, "Auth Middleware", "Controller | TypeScript", "Middleware for Authentication\n(mos-user-service)")
Component(getPemKey, "getPemKey", "Function | TypeScript", "Function for Get Pemkey\n(mos-user-service)")

Component(user_controller, "User Controller", "Controller | TypeScript", "Controller for User Related Function\n(mos-user-service)")
Component(logout, "logout", "Function | TypeScript", "Function for Logout\n(mos-user-service)")

}
Rel_D(Web_Moservice, mainMiddleware, "1. Request Log Out")

Rel_D(mainMiddleware, auth_middleware, "2. Request Log Out")
Rel_R(auth_middleware, getPemKey, "3. Get Pem Key")

Rel_D(auth_middleware, user_controller, "4. Request Log Out")
Rel_D(user_controller, logout, "5. Do Log Out Process")

@enduml